# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class UpdateCameraGroupPromptBindingRequest(BaseModel):
    """
    UpdateCameraGroupPromptBindingRequest
    """ # noqa: E501
    enabled: Optional[StrictBool] = None
    scan_frequency: Optional[StrictStr] = Field(default=None, alias="scanFrequency")
    priority_override: Optional[StrictStr] = Field(default=None, alias="priorityOverride")
    max_estimated_cost_override: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maxEstimatedCostOverride")
    __properties: ClassVar[List[str]] = ["enabled", "scanFrequency", "priorityOverride", "maxEstimatedCostOverride"]

    @field_validator('scan_frequency')
    def scan_frequency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['manual', 'hourly', 'daily', 'continuous']):
            raise ValueError("must be one of enum values ('manual', 'hourly', 'daily', 'continuous')")
        return value

    @field_validator('priority_override')
    def priority_override_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['low', 'normal', 'high', 'emergency']):
            raise ValueError("must be one of enum values ('low', 'normal', 'high', 'emergency')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateCameraGroupPromptBindingRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateCameraGroupPromptBindingRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled"),
            "scanFrequency": obj.get("scanFrequency"),
            "priorityOverride": obj.get("priorityOverride"),
            "maxEstimatedCostOverride": obj.get("maxEstimatedCostOverride")
        })
        return _obj


