/**
 * Camera System Integrator API
 * Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetCameraSnapshot200Response model module.
 * @module model/GetCameraSnapshot200Response
 * @version 0.1.0
 */
class GetCameraSnapshot200Response {
    /**
     * Constructs a new <code>GetCameraSnapshot200Response</code>.
     * @alias module:model/GetCameraSnapshot200Response
     * @param cameraId {String} 
     * @param capturedAt {Date} 
     * @param imageUrl {String} 
     */
    constructor(cameraId, capturedAt, imageUrl) { 
        
        GetCameraSnapshot200Response.initialize(this, cameraId, capturedAt, imageUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cameraId, capturedAt, imageUrl) { 
        obj['cameraId'] = cameraId;
        obj['capturedAt'] = capturedAt;
        obj['imageUrl'] = imageUrl;
    }

    /**
     * Constructs a <code>GetCameraSnapshot200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetCameraSnapshot200Response} obj Optional instance to populate.
     * @return {module:model/GetCameraSnapshot200Response} The populated <code>GetCameraSnapshot200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetCameraSnapshot200Response();

            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'String');
            }
            if (data.hasOwnProperty('capturedAt')) {
                obj['capturedAt'] = ApiClient.convertToType(data['capturedAt'], 'Date');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
            if (data.hasOwnProperty('mimeType')) {
                obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetCameraSnapshot200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetCameraSnapshot200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetCameraSnapshot200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['cameraId'] && !(typeof data['cameraId'] === 'string' || data['cameraId'] instanceof String)) {
            throw new Error("Expected the field `cameraId` to be a primitive type in the JSON string but got " + data['cameraId']);
        }
        // ensure the json data is a string
        if (data['imageUrl'] && !(typeof data['imageUrl'] === 'string' || data['imageUrl'] instanceof String)) {
            throw new Error("Expected the field `imageUrl` to be a primitive type in the JSON string but got " + data['imageUrl']);
        }
        // ensure the json data is a string
        if (data['mimeType'] && !(typeof data['mimeType'] === 'string' || data['mimeType'] instanceof String)) {
            throw new Error("Expected the field `mimeType` to be a primitive type in the JSON string but got " + data['mimeType']);
        }

        return true;
    }


}

GetCameraSnapshot200Response.RequiredProperties = ["cameraId", "capturedAt", "imageUrl"];

/**
 * @member {String} cameraId
 */
GetCameraSnapshot200Response.prototype['cameraId'] = undefined;

/**
 * @member {Date} capturedAt
 */
GetCameraSnapshot200Response.prototype['capturedAt'] = undefined;

/**
 * @member {String} imageUrl
 */
GetCameraSnapshot200Response.prototype['imageUrl'] = undefined;

/**
 * @member {String} mimeType
 */
GetCameraSnapshot200Response.prototype['mimeType'] = undefined;

/**
 * @member {Number} width
 */
GetCameraSnapshot200Response.prototype['width'] = undefined;

/**
 * @member {Number} height
 */
GetCameraSnapshot200Response.prototype['height'] = undefined;






export default GetCameraSnapshot200Response;

