/**
 * Camera System Integrator API
 * Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListIntegratorCameraGroups200ResponseGroupsInner from './ListIntegratorCameraGroups200ResponseGroupsInner';

/**
 * The ListIntegratorCameraGroups200Response model module.
 * @module model/ListIntegratorCameraGroups200Response
 * @version 0.1.0
 */
class ListIntegratorCameraGroups200Response {
    /**
     * Constructs a new <code>ListIntegratorCameraGroups200Response</code>.
     * @alias module:model/ListIntegratorCameraGroups200Response
     * @param groups {Array.<module:model/ListIntegratorCameraGroups200ResponseGroupsInner>} 
     */
    constructor(groups) { 
        
        ListIntegratorCameraGroups200Response.initialize(this, groups);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, groups) { 
        obj['groups'] = groups;
    }

    /**
     * Constructs a <code>ListIntegratorCameraGroups200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListIntegratorCameraGroups200Response} obj Optional instance to populate.
     * @return {module:model/ListIntegratorCameraGroups200Response} The populated <code>ListIntegratorCameraGroups200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListIntegratorCameraGroups200Response();

            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [ListIntegratorCameraGroups200ResponseGroupsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListIntegratorCameraGroups200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListIntegratorCameraGroups200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListIntegratorCameraGroups200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['groups']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['groups'])) {
                throw new Error("Expected the field `groups` to be an array in the JSON data but got " + data['groups']);
            }
            // validate the optional field `groups` (array)
            for (const item of data['groups']) {
                ListIntegratorCameraGroups200ResponseGroupsInner.validateJSON(item);
            };
        }

        return true;
    }


}

ListIntegratorCameraGroups200Response.RequiredProperties = ["groups"];

/**
 * @member {Array.<module:model/ListIntegratorCameraGroups200ResponseGroupsInner>} groups
 */
ListIntegratorCameraGroups200Response.prototype['groups'] = undefined;






export default ListIntegratorCameraGroups200Response;

