/**
 * Camera System Integrator API
 * Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestCameraSnapshot200Response model module.
 * @module model/RequestCameraSnapshot200Response
 * @version 0.1.0
 */
class RequestCameraSnapshot200Response {
    /**
     * Constructs a new <code>RequestCameraSnapshot200Response</code>.
     * @alias module:model/RequestCameraSnapshot200Response
     * @param snapshotId {String} Opaque id for this returned snapshot. This is not a source frame number.
     * @param cameraId {String} 
     * @param sequenceNumber {Number} Monotonic per-camera request sequence assigned by the adapter. Useful for ordering/debugging, not for selecting frames.
     * @param capturedAt {Date} 
     * @param imageUrl {String} Stable image URL for this requested snapshot. Repeated snapshot requests return different image URLs/snapshotIds as the cursor advances.
     */
    constructor(snapshotId, cameraId, sequenceNumber, capturedAt, imageUrl) { 
        
        RequestCameraSnapshot200Response.initialize(this, snapshotId, cameraId, sequenceNumber, capturedAt, imageUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, snapshotId, cameraId, sequenceNumber, capturedAt, imageUrl) { 
        obj['snapshotId'] = snapshotId;
        obj['cameraId'] = cameraId;
        obj['sequenceNumber'] = sequenceNumber;
        obj['capturedAt'] = capturedAt;
        obj['imageUrl'] = imageUrl;
    }

    /**
     * Constructs a <code>RequestCameraSnapshot200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestCameraSnapshot200Response} obj Optional instance to populate.
     * @return {module:model/RequestCameraSnapshot200Response} The populated <code>RequestCameraSnapshot200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestCameraSnapshot200Response();

            if (data.hasOwnProperty('snapshotId')) {
                obj['snapshotId'] = ApiClient.convertToType(data['snapshotId'], 'String');
            }
            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'String');
            }
            if (data.hasOwnProperty('sequenceNumber')) {
                obj['sequenceNumber'] = ApiClient.convertToType(data['sequenceNumber'], 'Number');
            }
            if (data.hasOwnProperty('capturedAt')) {
                obj['capturedAt'] = ApiClient.convertToType(data['capturedAt'], 'Date');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
            if (data.hasOwnProperty('mimeType')) {
                obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RequestCameraSnapshot200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RequestCameraSnapshot200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RequestCameraSnapshot200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['snapshotId'] && !(typeof data['snapshotId'] === 'string' || data['snapshotId'] instanceof String)) {
            throw new Error("Expected the field `snapshotId` to be a primitive type in the JSON string but got " + data['snapshotId']);
        }
        // ensure the json data is a string
        if (data['cameraId'] && !(typeof data['cameraId'] === 'string' || data['cameraId'] instanceof String)) {
            throw new Error("Expected the field `cameraId` to be a primitive type in the JSON string but got " + data['cameraId']);
        }
        // ensure the json data is a string
        if (data['imageUrl'] && !(typeof data['imageUrl'] === 'string' || data['imageUrl'] instanceof String)) {
            throw new Error("Expected the field `imageUrl` to be a primitive type in the JSON string but got " + data['imageUrl']);
        }
        // ensure the json data is a string
        if (data['mimeType'] && !(typeof data['mimeType'] === 'string' || data['mimeType'] instanceof String)) {
            throw new Error("Expected the field `mimeType` to be a primitive type in the JSON string but got " + data['mimeType']);
        }

        return true;
    }


}

RequestCameraSnapshot200Response.RequiredProperties = ["snapshotId", "cameraId", "sequenceNumber", "capturedAt", "imageUrl"];

/**
 * Opaque id for this returned snapshot. This is not a source frame number.
 * @member {String} snapshotId
 */
RequestCameraSnapshot200Response.prototype['snapshotId'] = undefined;

/**
 * @member {String} cameraId
 */
RequestCameraSnapshot200Response.prototype['cameraId'] = undefined;

/**
 * Monotonic per-camera request sequence assigned by the adapter. Useful for ordering/debugging, not for selecting frames.
 * @member {Number} sequenceNumber
 */
RequestCameraSnapshot200Response.prototype['sequenceNumber'] = undefined;

/**
 * @member {Date} capturedAt
 */
RequestCameraSnapshot200Response.prototype['capturedAt'] = undefined;

/**
 * Stable image URL for this requested snapshot. Repeated snapshot requests return different image URLs/snapshotIds as the cursor advances.
 * @member {String} imageUrl
 */
RequestCameraSnapshot200Response.prototype['imageUrl'] = undefined;

/**
 * @member {String} mimeType
 */
RequestCameraSnapshot200Response.prototype['mimeType'] = undefined;

/**
 * @member {Number} width
 */
RequestCameraSnapshot200Response.prototype['width'] = undefined;

/**
 * @member {Number} height
 */
RequestCameraSnapshot200Response.prototype['height'] = undefined;






export default RequestCameraSnapshot200Response;

