# coding: utf-8

# flake8: noqa

"""
    Camera System Integrator API

    Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from camera_system_integrator_dtos.api.cameras_api import CamerasApi
from camera_system_integrator_dtos.api.snapshots_api import SnapshotsApi
from camera_system_integrator_dtos.api.source_camera_groups_api import SourceCameraGroupsApi
from camera_system_integrator_dtos.api.streams_api import StreamsApi
from camera_system_integrator_dtos.api.system_api import SystemApi

# import ApiClient
from camera_system_integrator_dtos.api_response import ApiResponse
from camera_system_integrator_dtos.api_client import ApiClient
from camera_system_integrator_dtos.configuration import Configuration
from camera_system_integrator_dtos.exceptions import OpenApiException
from camera_system_integrator_dtos.exceptions import ApiTypeError
from camera_system_integrator_dtos.exceptions import ApiValueError
from camera_system_integrator_dtos.exceptions import ApiKeyError
from camera_system_integrator_dtos.exceptions import ApiAttributeError
from camera_system_integrator_dtos.exceptions import ApiException

# import models into sdk package
from camera_system_integrator_dtos.models.get_camera_frame_url200_response import GetCameraFrameUrl200Response
from camera_system_integrator_dtos.models.get_camera_snapshot200_response import GetCameraSnapshot200Response
from camera_system_integrator_dtos.models.get_camera_snapshot200_response_frame import GetCameraSnapshot200ResponseFrame
from camera_system_integrator_dtos.models.get_camera_stream200_response import GetCameraStream200Response
from camera_system_integrator_dtos.models.get_camera_system_status200_response import GetCameraSystemStatus200Response
from camera_system_integrator_dtos.models.inline_object import InlineObject
from camera_system_integrator_dtos.models.list_integrator_camera_groups200_response import ListIntegratorCameraGroups200Response
from camera_system_integrator_dtos.models.list_integrator_camera_groups200_response_groups_inner import ListIntegratorCameraGroups200ResponseGroupsInner
from camera_system_integrator_dtos.models.list_integrator_cameras200_response import ListIntegratorCameras200Response
from camera_system_integrator_dtos.models.list_integrator_cameras200_response_cameras_inner import ListIntegratorCameras200ResponseCamerasInner
