# coding: utf-8

"""
    Camera System Integrator API

    Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from camera_system_integrator_dtos.models.get_camera_snapshot200_response import GetCameraSnapshot200Response

class TestGetCameraSnapshot200Response(unittest.TestCase):
    """GetCameraSnapshot200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCameraSnapshot200Response:
        """Test GetCameraSnapshot200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCameraSnapshot200Response`
        """
        model = GetCameraSnapshot200Response()
        if include_optional:
            return GetCameraSnapshot200Response(
                snapshot_id = 'snap-camera-main-entrance-01-000001',
                camera_id = 'camera-main-entrance-01',
                frame = camera_system_integrator_dtos.models.get_camera_snapshot_200_response_frame.getCameraSnapshot_200_response_frame(
                    frame_id = 'frame-camera-main-entrance-01-000001', 
                    sequence_number = 1, 
                    captured_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    url = '/camera-system/cameras/camera-main-entrance-01/frames/frame-camera-main-entrance-01-000001/image', 
                    mime_type = 'image/jpeg', 
                    width = 1280, 
                    height = 720, 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return GetCameraSnapshot200Response(
                snapshot_id = 'snap-camera-main-entrance-01-000001',
                camera_id = 'camera-main-entrance-01',
                frame = camera_system_integrator_dtos.models.get_camera_snapshot_200_response_frame.getCameraSnapshot_200_response_frame(
                    frame_id = 'frame-camera-main-entrance-01-000001', 
                    sequence_number = 1, 
                    captured_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    url = '/camera-system/cameras/camera-main-entrance-01/frames/frame-camera-main-entrance-01-000001/image', 
                    mime_type = 'image/jpeg', 
                    width = 1280, 
                    height = 720, 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testGetCameraSnapshot200Response(self):
        """Test GetCameraSnapshot200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
