# coding: utf-8

"""
    Camera System Integrator API

    Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from camera_system_integrator_dtos.models.get_camera_system_status200_response import GetCameraSystemStatus200Response

class TestGetCameraSystemStatus200Response(unittest.TestCase):
    """GetCameraSystemStatus200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCameraSystemStatus200Response:
        """Test GetCameraSystemStatus200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCameraSystemStatus200Response`
        """
        model = GetCameraSystemStatus200Response()
        if include_optional:
            return GetCameraSystemStatus200Response(
                status = 'healthy',
                checked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                camera_count = 128,
                online_camera_count = 121,
                message = ''
            )
        else:
            return GetCameraSystemStatus200Response(
                status = 'healthy',
                checked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testGetCameraSystemStatus200Response(self):
        """Test GetCameraSystemStatus200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
