/**
 * Camera System Integrator API
 * Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import GetCameraSnapshot200Response from './model/GetCameraSnapshot200Response';
import GetCameraStream200Response from './model/GetCameraStream200Response';
import GetCameraSystemStatus200Response from './model/GetCameraSystemStatus200Response';
import ListIntegratorCameraGroups200Response from './model/ListIntegratorCameraGroups200Response';
import ListIntegratorCameraGroups200ResponseGroupsInner from './model/ListIntegratorCameraGroups200ResponseGroupsInner';
import ListIntegratorCameras200Response from './model/ListIntegratorCameras200Response';
import ListIntegratorCameras200ResponseCamerasInner from './model/ListIntegratorCameras200ResponseCamerasInner';
import CamerasApi from './api/CamerasApi';
import SnapshotsApi from './api/SnapshotsApi';
import SourceCameraGroupsApi from './api/SourceCameraGroupsApi';
import StreamsApi from './api/StreamsApi';
import SystemApi from './api/SystemApi';


/**
* Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CameraSystemIntegratorApi = require('index'); // See note below*.
* var xxxSvc = new CameraSystemIntegratorApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CameraSystemIntegratorApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CameraSystemIntegratorApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CameraSystemIntegratorApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The GetCameraSnapshot200Response model constructor.
     * @property {module:model/GetCameraSnapshot200Response}
     */
    GetCameraSnapshot200Response,

    /**
     * The GetCameraStream200Response model constructor.
     * @property {module:model/GetCameraStream200Response}
     */
    GetCameraStream200Response,

    /**
     * The GetCameraSystemStatus200Response model constructor.
     * @property {module:model/GetCameraSystemStatus200Response}
     */
    GetCameraSystemStatus200Response,

    /**
     * The ListIntegratorCameraGroups200Response model constructor.
     * @property {module:model/ListIntegratorCameraGroups200Response}
     */
    ListIntegratorCameraGroups200Response,

    /**
     * The ListIntegratorCameraGroups200ResponseGroupsInner model constructor.
     * @property {module:model/ListIntegratorCameraGroups200ResponseGroupsInner}
     */
    ListIntegratorCameraGroups200ResponseGroupsInner,

    /**
     * The ListIntegratorCameras200Response model constructor.
     * @property {module:model/ListIntegratorCameras200Response}
     */
    ListIntegratorCameras200Response,

    /**
     * The ListIntegratorCameras200ResponseCamerasInner model constructor.
     * @property {module:model/ListIntegratorCameras200ResponseCamerasInner}
     */
    ListIntegratorCameras200ResponseCamerasInner,

    /**
    * The CamerasApi service constructor.
    * @property {module:api/CamerasApi}
    */
    CamerasApi,

    /**
    * The SnapshotsApi service constructor.
    * @property {module:api/SnapshotsApi}
    */
    SnapshotsApi,

    /**
    * The SourceCameraGroupsApi service constructor.
    * @property {module:api/SourceCameraGroupsApi}
    */
    SourceCameraGroupsApi,

    /**
    * The StreamsApi service constructor.
    * @property {module:api/StreamsApi}
    */
    StreamsApi,

    /**
    * The SystemApi service constructor.
    * @property {module:api/SystemApi}
    */
    SystemApi
};
