# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.create_operator_queue_item_request import CreateOperatorQueueItemRequest

class TestCreateOperatorQueueItemRequest(unittest.TestCase):
    """CreateOperatorQueueItemRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOperatorQueueItemRequest:
        """Test CreateOperatorQueueItemRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOperatorQueueItemRequest`
        """
        model = CreateOperatorQueueItemRequest()
        if include_optional:
            return CreateOperatorQueueItemRequest(
                second_pass_result_id = ''
            )
        else:
            return CreateOperatorQueueItemRequest(
                second_pass_result_id = '',
        )
        """

    def testCreateOperatorQueueItemRequest(self):
        """Test CreateOperatorQueueItemRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
