# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.list_saved_prompts200_response_prompts_inner import ListSavedPrompts200ResponsePromptsInner

class TestListSavedPrompts200ResponsePromptsInner(unittest.TestCase):
    """ListSavedPrompts200ResponsePromptsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSavedPrompts200ResponsePromptsInner:
        """Test ListSavedPrompts200ResponsePromptsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListSavedPrompts200ResponsePromptsInner`
        """
        model = ListSavedPrompts200ResponsePromptsInner()
        if include_optional:
            return ListSavedPrompts200ResponsePromptsInner(
                id = 'prompt-ice-near-entrances',
                name = 'Ice near entrances',
                description = 'Checks entrance snapshots for ice, snow, slick surfaces, or blocked paths.',
                prompt_text = 'Inspect this camera snapshot for ice, snow, slick surfaces, blocked entrances, or other conditions that require staff action. Return structured JSON only.',
                enabled = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ListSavedPrompts200ResponsePromptsInner(
                id = 'prompt-ice-near-entrances',
                name = 'Ice near entrances',
                prompt_text = 'Inspect this camera snapshot for ice, snow, slick surfaces, blocked entrances, or other conditions that require staff action. Return structured JSON only.',
                enabled = True,
        )
        """

    def testListSavedPrompts200ResponsePromptsInner(self):
        """Test ListSavedPrompts200ResponsePromptsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
