# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.create_operation_request import CreateOperationRequest

class TestCreateOperationRequest(unittest.TestCase):
    """CreateOperationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOperationRequest:
        """Test CreateOperationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOperationRequest`
        """
        model = CreateOperationRequest()
        if include_optional:
            return CreateOperationRequest(
                operation_type = 'find',
                target = cambot_dtos.models.estimate_operation_request_target.estimateOperation_request_target(
                    type = 'camera', 
                    camera_id = '', 
                    camera_group_id = '', ),
                saved_prompt_id = '',
                temporary_prompt_text = '',
                max_estimated_cost = 1.337
            )
        else:
            return CreateOperationRequest(
                operation_type = 'find',
                target = cambot_dtos.models.estimate_operation_request_target.estimateOperation_request_target(
                    type = 'camera', 
                    camera_id = '', 
                    camera_group_id = '', ),
        )
        """

    def testCreateOperationRequest(self):
        """Test CreateOperationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
