# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.get_gemini_caller_settings200_response import GetGeminiCallerSettings200Response

class TestGetGeminiCallerSettings200Response(unittest.TestCase):
    """GetGeminiCallerSettings200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGeminiCallerSettings200Response:
        """Test GetGeminiCallerSettings200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGeminiCallerSettings200Response`
        """
        model = GetGeminiCallerSettings200Response()
        if include_optional:
            return GetGeminiCallerSettings200Response(
                enabled = True,
                model_name = 'gemini-1.5-flash',
                continuous_scan_enabled = True,
                continuous_scan_interval_seconds = 900,
                last_continuous_scan_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                next_continuous_scan_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                gemini_call_delay_ms = 2000,
                max_concurrent_gemini_calls = 1,
                max_tokens_per_request = 8192,
                max_cost_per_day = 25.0,
                max_cost_per_month = 300.0,
                allow_emergency_override = True,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetGeminiCallerSettings200Response(
        )
        """

    def testGetGeminiCallerSettings200Response(self):
        """Test GetGeminiCallerSettings200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
