# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.get_usage_limit_settings200_response import GetUsageLimitSettings200Response

class TestGetUsageLimitSettings200Response(unittest.TestCase):
    """GetUsageLimitSettings200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUsageLimitSettings200Response:
        """Test GetUsageLimitSettings200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUsageLimitSettings200Response`
        """
        model = GetUsageLimitSettings200Response()
        if include_optional:
            return GetUsageLimitSettings200Response(
                max_scans_per_day = 500,
                max_scans_per_month = 10000,
                max_estimated_cost_per_day = 25.0,
                max_estimated_cost_per_month = 300.0,
                block_operations_when_limit_reached = True,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetUsageLimitSettings200Response(
        )
        """

    def testGetUsageLimitSettings200Response(self):
        """Test GetUsageLimitSettings200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
