# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.list_proxied_integrator_cameras200_response import ListProxiedIntegratorCameras200Response

class TestListProxiedIntegratorCameras200Response(unittest.TestCase):
    """ListProxiedIntegratorCameras200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListProxiedIntegratorCameras200Response:
        """Test ListProxiedIntegratorCameras200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListProxiedIntegratorCameras200Response`
        """
        model = ListProxiedIntegratorCameras200Response()
        if include_optional:
            return ListProxiedIntegratorCameras200Response(
                cameras = [
                    cambot_dtos.models.list_proxied_integrator_cameras_200_response_cameras_inner.listProxiedIntegratorCameras_200_response_cameras_inner(
                        id = 'camera-main-entrance-01', 
                        name = 'Main Entrance 01', 
                        description = '', 
                        location = 'Building A Main Entrance', 
                        group_ids = [
                            ''
                            ], 
                        status = 'online', 
                        stream_available = True, 
                        snapshot_available = True, 
                        vendor_metadata = { }, )
                    ]
            )
        else:
            return ListProxiedIntegratorCameras200Response(
                cameras = [
                    cambot_dtos.models.list_proxied_integrator_cameras_200_response_cameras_inner.listProxiedIntegratorCameras_200_response_cameras_inner(
                        id = 'camera-main-entrance-01', 
                        name = 'Main Entrance 01', 
                        description = '', 
                        location = 'Building A Main Entrance', 
                        group_ids = [
                            ''
                            ], 
                        status = 'online', 
                        stream_available = True, 
                        snapshot_available = True, 
                        vendor_metadata = { }, )
                    ],
        )
        """

    def testListProxiedIntegratorCameras200Response(self):
        """Test ListProxiedIntegratorCameras200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
