# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.api.settings_api import SettingsApi


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingsApi()

    def tearDown(self) -> None:
        pass

    def test_get_gemini_caller_settings(self) -> None:
        """Test case for get_gemini_caller_settings

        Get Gemini caller settings
        """
        pass

    def test_get_usage_limit_settings(self) -> None:
        """Test case for get_usage_limit_settings

        Get usage limit settings
        """
        pass

    def test_update_gemini_caller_settings(self) -> None:
        """Test case for update_gemini_caller_settings

        Update Gemini caller settings
        """
        pass

    def test_update_usage_limit_settings(self) -> None:
        """Test case for update_usage_limit_settings

        Update usage limit settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
