/**
 * Camera System Integrator API
 * Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CameraSystemIntegratorApi);
  }
}(this, function(expect, CameraSystemIntegratorApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListIntegratorCameras200ResponseCamerasInner', function() {
    it('should create an instance of ListIntegratorCameras200ResponseCamerasInner', function() {
      // uncomment below and update the code to test ListIntegratorCameras200ResponseCamerasInner
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner();
      //expect(instance).to.be.a(CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner();
      //expect(instance).to.be();
    });

    it('should have the property groupIds (base name: "groupIds")', function() {
      // uncomment below and update the code to test the property groupIds
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner();
      //expect(instance).to.be();
    });

    it('should have the property streamAvailable (base name: "streamAvailable")', function() {
      // uncomment below and update the code to test the property streamAvailable
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner();
      //expect(instance).to.be();
    });

    it('should have the property snapshotAvailable (base name: "snapshotAvailable")', function() {
      // uncomment below and update the code to test the property snapshotAvailable
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner();
      //expect(instance).to.be();
    });

    it('should have the property vendorMetadata (base name: "vendorMetadata")', function() {
      // uncomment below and update the code to test the property vendorMetadata
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200ResponseCamerasInner();
      //expect(instance).to.be();
    });

  });

}));
