/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListCameraGroups200ResponseGroupsInnerStats model module.
 * @module model/ListCameraGroups200ResponseGroupsInnerStats
 * @version 0.1.0
 */
class ListCameraGroups200ResponseGroupsInnerStats {
    /**
     * Constructs a new <code>ListCameraGroups200ResponseGroupsInnerStats</code>.
     * @alias module:model/ListCameraGroups200ResponseGroupsInnerStats
     */
    constructor() { 
        
        ListCameraGroups200ResponseGroupsInnerStats.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListCameraGroups200ResponseGroupsInnerStats</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListCameraGroups200ResponseGroupsInnerStats} obj Optional instance to populate.
     * @return {module:model/ListCameraGroups200ResponseGroupsInnerStats} The populated <code>ListCameraGroups200ResponseGroupsInnerStats</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListCameraGroups200ResponseGroupsInnerStats();

            if (data.hasOwnProperty('cameraCount')) {
                obj['cameraCount'] = ApiClient.convertToType(data['cameraCount'], 'Number');
            }
            if (data.hasOwnProperty('appliedPromptCount')) {
                obj['appliedPromptCount'] = ApiClient.convertToType(data['appliedPromptCount'], 'Number');
            }
            if (data.hasOwnProperty('enabledPromptCount')) {
                obj['enabledPromptCount'] = ApiClient.convertToType(data['enabledPromptCount'], 'Number');
            }
            if (data.hasOwnProperty('scansPerDay')) {
                obj['scansPerDay'] = ApiClient.convertToType(data['scansPerDay'], 'Number');
            }
            if (data.hasOwnProperty('estimatedCostPerScan')) {
                obj['estimatedCostPerScan'] = ApiClient.convertToType(data['estimatedCostPerScan'], 'Number');
            }
            if (data.hasOwnProperty('estimatedCostPerDay')) {
                obj['estimatedCostPerDay'] = ApiClient.convertToType(data['estimatedCostPerDay'], 'Number');
            }
            if (data.hasOwnProperty('estimatedCostPerMonth')) {
                obj['estimatedCostPerMonth'] = ApiClient.convertToType(data['estimatedCostPerMonth'], 'Number');
            }
            if (data.hasOwnProperty('lastScannedAt')) {
                obj['lastScannedAt'] = ApiClient.convertToType(data['lastScannedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListCameraGroups200ResponseGroupsInnerStats</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListCameraGroups200ResponseGroupsInnerStats</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} cameraCount
 */
ListCameraGroups200ResponseGroupsInnerStats.prototype['cameraCount'] = undefined;

/**
 * @member {Number} appliedPromptCount
 */
ListCameraGroups200ResponseGroupsInnerStats.prototype['appliedPromptCount'] = undefined;

/**
 * @member {Number} enabledPromptCount
 */
ListCameraGroups200ResponseGroupsInnerStats.prototype['enabledPromptCount'] = undefined;

/**
 * @member {Number} scansPerDay
 */
ListCameraGroups200ResponseGroupsInnerStats.prototype['scansPerDay'] = undefined;

/**
 * @member {Number} estimatedCostPerScan
 */
ListCameraGroups200ResponseGroupsInnerStats.prototype['estimatedCostPerScan'] = undefined;

/**
 * @member {Number} estimatedCostPerDay
 */
ListCameraGroups200ResponseGroupsInnerStats.prototype['estimatedCostPerDay'] = undefined;

/**
 * @member {Number} estimatedCostPerMonth
 */
ListCameraGroups200ResponseGroupsInnerStats.prototype['estimatedCostPerMonth'] = undefined;

/**
 * @member {Date} lastScannedAt
 */
ListCameraGroups200ResponseGroupsInnerStats.prototype['lastScannedAt'] = undefined;






export default ListCameraGroups200ResponseGroupsInnerStats;

