/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListOperatorQueueItems200ResponseItemsInnerScore model module.
 * @module model/ListOperatorQueueItems200ResponseItemsInnerScore
 * @version 0.1.0
 */
class ListOperatorQueueItems200ResponseItemsInnerScore {
    /**
     * Constructs a new <code>ListOperatorQueueItems200ResponseItemsInnerScore</code>.
     * @alias module:model/ListOperatorQueueItems200ResponseItemsInnerScore
     */
    constructor() { 
        
        ListOperatorQueueItems200ResponseItemsInnerScore.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListOperatorQueueItems200ResponseItemsInnerScore</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListOperatorQueueItems200ResponseItemsInnerScore} obj Optional instance to populate.
     * @return {module:model/ListOperatorQueueItems200ResponseItemsInnerScore} The populated <code>ListOperatorQueueItems200ResponseItemsInnerScore</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListOperatorQueueItems200ResponseItemsInnerScore();

            if (data.hasOwnProperty('confidence')) {
                obj['confidence'] = ApiClient.convertToType(data['confidence'], 'Number');
            }
            if (data.hasOwnProperty('urgency')) {
                obj['urgency'] = ApiClient.convertToType(data['urgency'], 'Number');
            }
            if (data.hasOwnProperty('risk')) {
                obj['risk'] = ApiClient.convertToType(data['risk'], 'Number');
            }
            if (data.hasOwnProperty('overall')) {
                obj['overall'] = ApiClient.convertToType(data['overall'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListOperatorQueueItems200ResponseItemsInnerScore</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListOperatorQueueItems200ResponseItemsInnerScore</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} confidence
 */
ListOperatorQueueItems200ResponseItemsInnerScore.prototype['confidence'] = undefined;

/**
 * @member {Number} urgency
 */
ListOperatorQueueItems200ResponseItemsInnerScore.prototype['urgency'] = undefined;

/**
 * @member {Number} risk
 */
ListOperatorQueueItems200ResponseItemsInnerScore.prototype['risk'] = undefined;

/**
 * @member {Number} overall
 */
ListOperatorQueueItems200ResponseItemsInnerScore.prototype['overall'] = undefined;






export default ListOperatorQueueItems200ResponseItemsInnerScore;

