/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListOperatorQueueItems200ResponseItemsInner from './ListOperatorQueueItems200ResponseItemsInner';

/**
 * The ListOperatorQueueItems200Response model module.
 * @module model/ListOperatorQueueItems200Response
 * @version 0.1.0
 */
class ListOperatorQueueItems200Response {
    /**
     * Constructs a new <code>ListOperatorQueueItems200Response</code>.
     * @alias module:model/ListOperatorQueueItems200Response
     * @param items {Array.<module:model/ListOperatorQueueItems200ResponseItemsInner>} 
     */
    constructor(items) { 
        
        ListOperatorQueueItems200Response.initialize(this, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items) { 
        obj['items'] = items;
    }

    /**
     * Constructs a <code>ListOperatorQueueItems200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListOperatorQueueItems200Response} obj Optional instance to populate.
     * @return {module:model/ListOperatorQueueItems200Response} The populated <code>ListOperatorQueueItems200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListOperatorQueueItems200Response();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [ListOperatorQueueItems200ResponseItemsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListOperatorQueueItems200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListOperatorQueueItems200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListOperatorQueueItems200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                ListOperatorQueueItems200ResponseItemsInner.validateJSON(item);
            };
        }

        return true;
    }


}

ListOperatorQueueItems200Response.RequiredProperties = ["items"];

/**
 * @member {Array.<module:model/ListOperatorQueueItems200ResponseItemsInner>} items
 */
ListOperatorQueueItems200Response.prototype['items'] = undefined;






export default ListOperatorQueueItems200Response;

