/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateUsageLimitSettingsRequest model module.
 * @module model/UpdateUsageLimitSettingsRequest
 * @version 0.1.0
 */
class UpdateUsageLimitSettingsRequest {
    /**
     * Constructs a new <code>UpdateUsageLimitSettingsRequest</code>.
     * @alias module:model/UpdateUsageLimitSettingsRequest
     */
    constructor() { 
        
        UpdateUsageLimitSettingsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateUsageLimitSettingsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateUsageLimitSettingsRequest} obj Optional instance to populate.
     * @return {module:model/UpdateUsageLimitSettingsRequest} The populated <code>UpdateUsageLimitSettingsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateUsageLimitSettingsRequest();

            if (data.hasOwnProperty('maxScansPerDay')) {
                obj['maxScansPerDay'] = ApiClient.convertToType(data['maxScansPerDay'], 'Number');
            }
            if (data.hasOwnProperty('maxScansPerMonth')) {
                obj['maxScansPerMonth'] = ApiClient.convertToType(data['maxScansPerMonth'], 'Number');
            }
            if (data.hasOwnProperty('maxEstimatedCostPerDay')) {
                obj['maxEstimatedCostPerDay'] = ApiClient.convertToType(data['maxEstimatedCostPerDay'], 'Number');
            }
            if (data.hasOwnProperty('maxEstimatedCostPerMonth')) {
                obj['maxEstimatedCostPerMonth'] = ApiClient.convertToType(data['maxEstimatedCostPerMonth'], 'Number');
            }
            if (data.hasOwnProperty('blockOperationsWhenLimitReached')) {
                obj['blockOperationsWhenLimitReached'] = ApiClient.convertToType(data['blockOperationsWhenLimitReached'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateUsageLimitSettingsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateUsageLimitSettingsRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} maxScansPerDay
 */
UpdateUsageLimitSettingsRequest.prototype['maxScansPerDay'] = undefined;

/**
 * @member {Number} maxScansPerMonth
 */
UpdateUsageLimitSettingsRequest.prototype['maxScansPerMonth'] = undefined;

/**
 * @member {Number} maxEstimatedCostPerDay
 */
UpdateUsageLimitSettingsRequest.prototype['maxEstimatedCostPerDay'] = undefined;

/**
 * @member {Number} maxEstimatedCostPerMonth
 */
UpdateUsageLimitSettingsRequest.prototype['maxEstimatedCostPerMonth'] = undefined;

/**
 * @member {Boolean} blockOperationsWhenLimitReached
 */
UpdateUsageLimitSettingsRequest.prototype['blockOperationsWhenLimitReached'] = undefined;






export default UpdateUsageLimitSettingsRequest;

