/**
 * Camera System Integrator API
 * Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetCameraSnapshot200ResponseFrame model module.
 * @module model/GetCameraSnapshot200ResponseFrame
 * @version 0.1.0
 */
class GetCameraSnapshot200ResponseFrame {
    /**
     * Constructs a new <code>GetCameraSnapshot200ResponseFrame</code>.
     * @alias module:model/GetCameraSnapshot200ResponseFrame
     * @param frameId {String} Opaque id for the frame returned by the camera system adapter.
     * @param sequenceNumber {Number} Monotonic per-camera frame sequence assigned by the adapter. Useful for ordering/debugging, not for historical lookup unless the adapter explicitly supports that.
     * @param capturedAt {Date} 
     * @param url {String} URL link for the frame image. This may be an internal API URL, a CDN URL, or a signed vendor URL.
     * @param mimeType {String} 
     */
    constructor(frameId, sequenceNumber, capturedAt, url, mimeType) { 
        
        GetCameraSnapshot200ResponseFrame.initialize(this, frameId, sequenceNumber, capturedAt, url, mimeType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, frameId, sequenceNumber, capturedAt, url, mimeType) { 
        obj['frameId'] = frameId;
        obj['sequenceNumber'] = sequenceNumber;
        obj['capturedAt'] = capturedAt;
        obj['url'] = url;
        obj['mimeType'] = mimeType;
    }

    /**
     * Constructs a <code>GetCameraSnapshot200ResponseFrame</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetCameraSnapshot200ResponseFrame} obj Optional instance to populate.
     * @return {module:model/GetCameraSnapshot200ResponseFrame} The populated <code>GetCameraSnapshot200ResponseFrame</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetCameraSnapshot200ResponseFrame();

            if (data.hasOwnProperty('frameId')) {
                obj['frameId'] = ApiClient.convertToType(data['frameId'], 'String');
            }
            if (data.hasOwnProperty('sequenceNumber')) {
                obj['sequenceNumber'] = ApiClient.convertToType(data['sequenceNumber'], 'Number');
            }
            if (data.hasOwnProperty('capturedAt')) {
                obj['capturedAt'] = ApiClient.convertToType(data['capturedAt'], 'Date');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('mimeType')) {
                obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('expiresAt')) {
                obj['expiresAt'] = ApiClient.convertToType(data['expiresAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetCameraSnapshot200ResponseFrame</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetCameraSnapshot200ResponseFrame</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetCameraSnapshot200ResponseFrame.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['frameId'] && !(typeof data['frameId'] === 'string' || data['frameId'] instanceof String)) {
            throw new Error("Expected the field `frameId` to be a primitive type in the JSON string but got " + data['frameId']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['mimeType'] && !(typeof data['mimeType'] === 'string' || data['mimeType'] instanceof String)) {
            throw new Error("Expected the field `mimeType` to be a primitive type in the JSON string but got " + data['mimeType']);
        }

        return true;
    }


}

GetCameraSnapshot200ResponseFrame.RequiredProperties = ["frameId", "sequenceNumber", "capturedAt", "url", "mimeType"];

/**
 * Opaque id for the frame returned by the camera system adapter.
 * @member {String} frameId
 */
GetCameraSnapshot200ResponseFrame.prototype['frameId'] = undefined;

/**
 * Monotonic per-camera frame sequence assigned by the adapter. Useful for ordering/debugging, not for historical lookup unless the adapter explicitly supports that.
 * @member {Number} sequenceNumber
 */
GetCameraSnapshot200ResponseFrame.prototype['sequenceNumber'] = undefined;

/**
 * @member {Date} capturedAt
 */
GetCameraSnapshot200ResponseFrame.prototype['capturedAt'] = undefined;

/**
 * URL link for the frame image. This may be an internal API URL, a CDN URL, or a signed vendor URL.
 * @member {String} url
 */
GetCameraSnapshot200ResponseFrame.prototype['url'] = undefined;

/**
 * @member {String} mimeType
 */
GetCameraSnapshot200ResponseFrame.prototype['mimeType'] = undefined;

/**
 * @member {Number} width
 */
GetCameraSnapshot200ResponseFrame.prototype['width'] = undefined;

/**
 * @member {Number} height
 */
GetCameraSnapshot200ResponseFrame.prototype['height'] = undefined;

/**
 * When the frame URL expires, if the adapter returns signed or temporary URLs.
 * @member {Date} expiresAt
 */
GetCameraSnapshot200ResponseFrame.prototype['expiresAt'] = undefined;






export default GetCameraSnapshot200ResponseFrame;

