/**
 * Camera System Integrator API
 * Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListIntegratorCameras200ResponseCamerasInner model module.
 * @module model/ListIntegratorCameras200ResponseCamerasInner
 * @version 0.1.0
 */
class ListIntegratorCameras200ResponseCamerasInner {
    /**
     * Constructs a new <code>ListIntegratorCameras200ResponseCamerasInner</code>.
     * @alias module:model/ListIntegratorCameras200ResponseCamerasInner
     * @param id {String} 
     * @param name {String} 
     * @param status {module:model/ListIntegratorCameras200ResponseCamerasInner.StatusEnum} 
     */
    constructor(id, name, status) { 
        
        ListIntegratorCameras200ResponseCamerasInner.initialize(this, id, name, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, status) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>ListIntegratorCameras200ResponseCamerasInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListIntegratorCameras200ResponseCamerasInner} obj Optional instance to populate.
     * @return {module:model/ListIntegratorCameras200ResponseCamerasInner} The populated <code>ListIntegratorCameras200ResponseCamerasInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListIntegratorCameras200ResponseCamerasInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('groupIds')) {
                obj['groupIds'] = ApiClient.convertToType(data['groupIds'], ['String']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('streamAvailable')) {
                obj['streamAvailable'] = ApiClient.convertToType(data['streamAvailable'], 'Boolean');
            }
            if (data.hasOwnProperty('snapshotAvailable')) {
                obj['snapshotAvailable'] = ApiClient.convertToType(data['snapshotAvailable'], 'Boolean');
            }
            if (data.hasOwnProperty('vendorMetadata')) {
                obj['vendorMetadata'] = ApiClient.convertToType(data['vendorMetadata'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListIntegratorCameras200ResponseCamerasInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListIntegratorCameras200ResponseCamerasInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListIntegratorCameras200ResponseCamerasInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['location'] && !(typeof data['location'] === 'string' || data['location'] instanceof String)) {
            throw new Error("Expected the field `location` to be a primitive type in the JSON string but got " + data['location']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['groupIds'])) {
            throw new Error("Expected the field `groupIds` to be an array in the JSON data but got " + data['groupIds']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

ListIntegratorCameras200ResponseCamerasInner.RequiredProperties = ["id", "name", "status"];

/**
 * @member {String} id
 */
ListIntegratorCameras200ResponseCamerasInner.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ListIntegratorCameras200ResponseCamerasInner.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ListIntegratorCameras200ResponseCamerasInner.prototype['description'] = undefined;

/**
 * @member {String} location
 */
ListIntegratorCameras200ResponseCamerasInner.prototype['location'] = undefined;

/**
 * @member {Array.<String>} groupIds
 */
ListIntegratorCameras200ResponseCamerasInner.prototype['groupIds'] = undefined;

/**
 * @member {module:model/ListIntegratorCameras200ResponseCamerasInner.StatusEnum} status
 */
ListIntegratorCameras200ResponseCamerasInner.prototype['status'] = undefined;

/**
 * @member {Boolean} streamAvailable
 */
ListIntegratorCameras200ResponseCamerasInner.prototype['streamAvailable'] = undefined;

/**
 * @member {Boolean} snapshotAvailable
 */
ListIntegratorCameras200ResponseCamerasInner.prototype['snapshotAvailable'] = undefined;

/**
 * @member {Object.<String, Object>} vendorMetadata
 */
ListIntegratorCameras200ResponseCamerasInner.prototype['vendorMetadata'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ListIntegratorCameras200ResponseCamerasInner['StatusEnum'] = {

    /**
     * value: "online"
     * @const
     */
    "online": "online",

    /**
     * value: "offline"
     * @const
     */
    "offline": "offline",

    /**
     * value: "unknown"
     * @const
     */
    "unknown": "unknown"
};



export default ListIntegratorCameras200ResponseCamerasInner;

