/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateCameraGroupPromptBindingRequest from './model/CreateCameraGroupPromptBindingRequest';
import CreateCameraGroupRequest from './model/CreateCameraGroupRequest';
import CreateOperationRequest from './model/CreateOperationRequest';
import CreateOperatorQueueItemRequest from './model/CreateOperatorQueueItemRequest';
import CreateSavedPromptRequest from './model/CreateSavedPromptRequest';
import EstimateOperation200Response from './model/EstimateOperation200Response';
import EstimateOperationRequest from './model/EstimateOperationRequest';
import GetGeminiCallerSettings200Response from './model/GetGeminiCallerSettings200Response';
import GetUsageLimitSettings200Response from './model/GetUsageLimitSettings200Response';
import GetUsageSummary200Response from './model/GetUsageSummary200Response';
import ListCameraGroupPromptBindings200Response from './model/ListCameraGroupPromptBindings200Response';
import ListCameraGroupPromptBindings200ResponseBindingsInner from './model/ListCameraGroupPromptBindings200ResponseBindingsInner';
import ListCameraGroups200Response from './model/ListCameraGroups200Response';
import ListCameraGroups200ResponseGroupsInner from './model/ListCameraGroups200ResponseGroupsInner';
import ListCameraGroups200ResponseGroupsInnerStats from './model/ListCameraGroups200ResponseGroupsInnerStats';
import ListOperationResults200Response from './model/ListOperationResults200Response';
import ListOperationResults200ResponseResultsInner from './model/ListOperationResults200ResponseResultsInner';
import ListOperations200Response from './model/ListOperations200Response';
import ListOperations200ResponseOperationsInner from './model/ListOperations200ResponseOperationsInner';
import ListOperatorQueueItems200Response from './model/ListOperatorQueueItems200Response';
import ListOperatorQueueItems200ResponseItemsInner from './model/ListOperatorQueueItems200ResponseItemsInner';
import ListSavedPrompts200Response from './model/ListSavedPrompts200Response';
import ListSavedPrompts200ResponsePromptsInner from './model/ListSavedPrompts200ResponsePromptsInner';
import ReplaceCameraGroupCamerasRequest from './model/ReplaceCameraGroupCamerasRequest';
import UpdateCameraGroupPromptBindingRequest from './model/UpdateCameraGroupPromptBindingRequest';
import UpdateCameraGroupRequest from './model/UpdateCameraGroupRequest';
import UpdateGeminiCallerSettingsRequest from './model/UpdateGeminiCallerSettingsRequest';
import UpdateOperatorQueueItemRequest from './model/UpdateOperatorQueueItemRequest';
import UpdateSavedPromptRequest from './model/UpdateSavedPromptRequest';
import UpdateUsageLimitSettingsRequest from './model/UpdateUsageLimitSettingsRequest';
import CameraGroupsApi from './api/CameraGroupsApi';
import OperationsApi from './api/OperationsApi';
import OperatorQueueApi from './api/OperatorQueueApi';
import PromptBindingsApi from './api/PromptBindingsApi';
import SavedPromptsApi from './api/SavedPromptsApi';
import SettingsApi from './api/SettingsApi';
import UsageApi from './api/UsageApi';


/**
* Product API used by the CamBot client..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CambotApi = require('index'); // See note below*.
* var xxxSvc = new CambotApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CambotApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CambotApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CambotApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateCameraGroupPromptBindingRequest model constructor.
     * @property {module:model/CreateCameraGroupPromptBindingRequest}
     */
    CreateCameraGroupPromptBindingRequest,

    /**
     * The CreateCameraGroupRequest model constructor.
     * @property {module:model/CreateCameraGroupRequest}
     */
    CreateCameraGroupRequest,

    /**
     * The CreateOperationRequest model constructor.
     * @property {module:model/CreateOperationRequest}
     */
    CreateOperationRequest,

    /**
     * The CreateOperatorQueueItemRequest model constructor.
     * @property {module:model/CreateOperatorQueueItemRequest}
     */
    CreateOperatorQueueItemRequest,

    /**
     * The CreateSavedPromptRequest model constructor.
     * @property {module:model/CreateSavedPromptRequest}
     */
    CreateSavedPromptRequest,

    /**
     * The EstimateOperation200Response model constructor.
     * @property {module:model/EstimateOperation200Response}
     */
    EstimateOperation200Response,

    /**
     * The EstimateOperationRequest model constructor.
     * @property {module:model/EstimateOperationRequest}
     */
    EstimateOperationRequest,

    /**
     * The GetGeminiCallerSettings200Response model constructor.
     * @property {module:model/GetGeminiCallerSettings200Response}
     */
    GetGeminiCallerSettings200Response,

    /**
     * The GetUsageLimitSettings200Response model constructor.
     * @property {module:model/GetUsageLimitSettings200Response}
     */
    GetUsageLimitSettings200Response,

    /**
     * The GetUsageSummary200Response model constructor.
     * @property {module:model/GetUsageSummary200Response}
     */
    GetUsageSummary200Response,

    /**
     * The ListCameraGroupPromptBindings200Response model constructor.
     * @property {module:model/ListCameraGroupPromptBindings200Response}
     */
    ListCameraGroupPromptBindings200Response,

    /**
     * The ListCameraGroupPromptBindings200ResponseBindingsInner model constructor.
     * @property {module:model/ListCameraGroupPromptBindings200ResponseBindingsInner}
     */
    ListCameraGroupPromptBindings200ResponseBindingsInner,

    /**
     * The ListCameraGroups200Response model constructor.
     * @property {module:model/ListCameraGroups200Response}
     */
    ListCameraGroups200Response,

    /**
     * The ListCameraGroups200ResponseGroupsInner model constructor.
     * @property {module:model/ListCameraGroups200ResponseGroupsInner}
     */
    ListCameraGroups200ResponseGroupsInner,

    /**
     * The ListCameraGroups200ResponseGroupsInnerStats model constructor.
     * @property {module:model/ListCameraGroups200ResponseGroupsInnerStats}
     */
    ListCameraGroups200ResponseGroupsInnerStats,

    /**
     * The ListOperationResults200Response model constructor.
     * @property {module:model/ListOperationResults200Response}
     */
    ListOperationResults200Response,

    /**
     * The ListOperationResults200ResponseResultsInner model constructor.
     * @property {module:model/ListOperationResults200ResponseResultsInner}
     */
    ListOperationResults200ResponseResultsInner,

    /**
     * The ListOperations200Response model constructor.
     * @property {module:model/ListOperations200Response}
     */
    ListOperations200Response,

    /**
     * The ListOperations200ResponseOperationsInner model constructor.
     * @property {module:model/ListOperations200ResponseOperationsInner}
     */
    ListOperations200ResponseOperationsInner,

    /**
     * The ListOperatorQueueItems200Response model constructor.
     * @property {module:model/ListOperatorQueueItems200Response}
     */
    ListOperatorQueueItems200Response,

    /**
     * The ListOperatorQueueItems200ResponseItemsInner model constructor.
     * @property {module:model/ListOperatorQueueItems200ResponseItemsInner}
     */
    ListOperatorQueueItems200ResponseItemsInner,

    /**
     * The ListSavedPrompts200Response model constructor.
     * @property {module:model/ListSavedPrompts200Response}
     */
    ListSavedPrompts200Response,

    /**
     * The ListSavedPrompts200ResponsePromptsInner model constructor.
     * @property {module:model/ListSavedPrompts200ResponsePromptsInner}
     */
    ListSavedPrompts200ResponsePromptsInner,

    /**
     * The ReplaceCameraGroupCamerasRequest model constructor.
     * @property {module:model/ReplaceCameraGroupCamerasRequest}
     */
    ReplaceCameraGroupCamerasRequest,

    /**
     * The UpdateCameraGroupPromptBindingRequest model constructor.
     * @property {module:model/UpdateCameraGroupPromptBindingRequest}
     */
    UpdateCameraGroupPromptBindingRequest,

    /**
     * The UpdateCameraGroupRequest model constructor.
     * @property {module:model/UpdateCameraGroupRequest}
     */
    UpdateCameraGroupRequest,

    /**
     * The UpdateGeminiCallerSettingsRequest model constructor.
     * @property {module:model/UpdateGeminiCallerSettingsRequest}
     */
    UpdateGeminiCallerSettingsRequest,

    /**
     * The UpdateOperatorQueueItemRequest model constructor.
     * @property {module:model/UpdateOperatorQueueItemRequest}
     */
    UpdateOperatorQueueItemRequest,

    /**
     * The UpdateSavedPromptRequest model constructor.
     * @property {module:model/UpdateSavedPromptRequest}
     */
    UpdateSavedPromptRequest,

    /**
     * The UpdateUsageLimitSettingsRequest model constructor.
     * @property {module:model/UpdateUsageLimitSettingsRequest}
     */
    UpdateUsageLimitSettingsRequest,

    /**
    * The CameraGroupsApi service constructor.
    * @property {module:api/CameraGroupsApi}
    */
    CameraGroupsApi,

    /**
    * The OperationsApi service constructor.
    * @property {module:api/OperationsApi}
    */
    OperationsApi,

    /**
    * The OperatorQueueApi service constructor.
    * @property {module:api/OperatorQueueApi}
    */
    OperatorQueueApi,

    /**
    * The PromptBindingsApi service constructor.
    * @property {module:api/PromptBindingsApi}
    */
    PromptBindingsApi,

    /**
    * The SavedPromptsApi service constructor.
    * @property {module:api/SavedPromptsApi}
    */
    SavedPromptsApi,

    /**
    * The SettingsApi service constructor.
    * @property {module:api/SettingsApi}
    */
    SettingsApi,

    /**
    * The UsageApi service constructor.
    * @property {module:api/UsageApi}
    */
    UsageApi
};
