/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateOperation201Response from '../model/CreateOperation201Response';
import CreateOperationRequest from '../model/CreateOperationRequest';
import EstimateOperation200Response from '../model/EstimateOperation200Response';
import EstimateOperationRequest from '../model/EstimateOperationRequest';

/**
* Operations service.
* @module api/OperationsApi
* @version 0.1.0
*/
export default class OperationsApi {

    /**
    * Constructs a new OperationsApi. 
    * @alias module:api/OperationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Start an AI operation
     * @param {module:model/CreateOperationRequest} createOperationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CreateOperation201Response} and HTTP response
     */
    createOperationWithHttpInfo(createOperationRequest) {
      let postBody = createOperationRequest;
      // verify the required parameter 'createOperationRequest' is set
      if (createOperationRequest === undefined || createOperationRequest === null) {
        throw new Error("Missing the required parameter 'createOperationRequest' when calling createOperation");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateOperation201Response;
      return this.apiClient.callApi(
        '/operations', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Start an AI operation
     * @param {module:model/CreateOperationRequest} createOperationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CreateOperation201Response}
     */
    createOperation(createOperationRequest) {
      return this.createOperationWithHttpInfo(createOperationRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Estimate operation usage and cost
     * @param {module:model/EstimateOperationRequest} estimateOperationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EstimateOperation200Response} and HTTP response
     */
    estimateOperationWithHttpInfo(estimateOperationRequest) {
      let postBody = estimateOperationRequest;
      // verify the required parameter 'estimateOperationRequest' is set
      if (estimateOperationRequest === undefined || estimateOperationRequest === null) {
        throw new Error("Missing the required parameter 'estimateOperationRequest' when calling estimateOperation");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EstimateOperation200Response;
      return this.apiClient.callApi(
        '/operations/estimate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Estimate operation usage and cost
     * @param {module:model/EstimateOperationRequest} estimateOperationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EstimateOperation200Response}
     */
    estimateOperation(estimateOperationRequest) {
      return this.estimateOperationWithHttpInfo(estimateOperationRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
