/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateOperatorQueueItemRequest from '../model/CreateOperatorQueueItemRequest';
import ListOperatorQueueItems200Response from '../model/ListOperatorQueueItems200Response';
import ListOperatorQueueItems200ResponseItemsInner from '../model/ListOperatorQueueItems200ResponseItemsInner';
import UpdateOperatorQueueItemRequest from '../model/UpdateOperatorQueueItemRequest';

/**
* OperatorQueue service.
* @module api/OperatorQueueApi
* @version 0.1.0
*/
export default class OperatorQueueApi {

    /**
    * Constructs a new OperatorQueueApi. 
    * @alias module:api/OperatorQueueApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create an operator queue item from a second-pass result
     * @param {module:model/CreateOperatorQueueItemRequest} createOperatorQueueItemRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListOperatorQueueItems200ResponseItemsInner} and HTTP response
     */
    createOperatorQueueItemWithHttpInfo(createOperatorQueueItemRequest) {
      let postBody = createOperatorQueueItemRequest;
      // verify the required parameter 'createOperatorQueueItemRequest' is set
      if (createOperatorQueueItemRequest === undefined || createOperatorQueueItemRequest === null) {
        throw new Error("Missing the required parameter 'createOperatorQueueItemRequest' when calling createOperatorQueueItem");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ListOperatorQueueItems200ResponseItemsInner;
      return this.apiClient.callApi(
        '/operator-queue', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create an operator queue item from a second-pass result
     * @param {module:model/CreateOperatorQueueItemRequest} createOperatorQueueItemRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListOperatorQueueItems200ResponseItemsInner}
     */
    createOperatorQueueItem(createOperatorQueueItemRequest) {
      return this.createOperatorQueueItemWithHttpInfo(createOperatorQueueItemRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List operator queue items
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [status] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListOperatorQueueItems200Response} and HTTP response
     */
    listOperatorQueueItemsWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'status': opts['status']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListOperatorQueueItems200Response;
      return this.apiClient.callApi(
        '/operator-queue', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List operator queue items
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.status 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListOperatorQueueItems200Response}
     */
    listOperatorQueueItems(opts) {
      return this.listOperatorQueueItemsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update operator queue item status
     * @param {String} queueItemId 
     * @param {module:model/UpdateOperatorQueueItemRequest} updateOperatorQueueItemRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListOperatorQueueItems200ResponseItemsInner} and HTTP response
     */
    updateOperatorQueueItemWithHttpInfo(queueItemId, updateOperatorQueueItemRequest) {
      let postBody = updateOperatorQueueItemRequest;
      // verify the required parameter 'queueItemId' is set
      if (queueItemId === undefined || queueItemId === null) {
        throw new Error("Missing the required parameter 'queueItemId' when calling updateOperatorQueueItem");
      }
      // verify the required parameter 'updateOperatorQueueItemRequest' is set
      if (updateOperatorQueueItemRequest === undefined || updateOperatorQueueItemRequest === null) {
        throw new Error("Missing the required parameter 'updateOperatorQueueItemRequest' when calling updateOperatorQueueItem");
      }

      let pathParams = {
        'queueItemId': queueItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ListOperatorQueueItems200ResponseItemsInner;
      return this.apiClient.callApi(
        '/operator-queue/{queueItemId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update operator queue item status
     * @param {String} queueItemId 
     * @param {module:model/UpdateOperatorQueueItemRequest} updateOperatorQueueItemRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListOperatorQueueItems200ResponseItemsInner}
     */
    updateOperatorQueueItem(queueItemId, updateOperatorQueueItemRequest) {
      return this.updateOperatorQueueItemWithHttpInfo(queueItemId, updateOperatorQueueItemRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
