# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.get_proxied_camera_system_status200_response import GetProxiedCameraSystemStatus200Response

class TestGetProxiedCameraSystemStatus200Response(unittest.TestCase):
    """GetProxiedCameraSystemStatus200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProxiedCameraSystemStatus200Response:
        """Test GetProxiedCameraSystemStatus200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProxiedCameraSystemStatus200Response`
        """
        model = GetProxiedCameraSystemStatus200Response()
        if include_optional:
            return GetProxiedCameraSystemStatus200Response(
                status = 'healthy',
                checked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                camera_count = 128,
                online_camera_count = 121,
                message = ''
            )
        else:
            return GetProxiedCameraSystemStatus200Response(
                status = 'healthy',
                checked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testGetProxiedCameraSystemStatus200Response(self):
        """Test GetProxiedCameraSystemStatus200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
