# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.list_operation_results200_response import ListOperationResults200Response

class TestListOperationResults200Response(unittest.TestCase):
    """ListOperationResults200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListOperationResults200Response:
        """Test ListOperationResults200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListOperationResults200Response`
        """
        model = ListOperationResults200Response()
        if include_optional:
            return ListOperationResults200Response(
                results = [
                    cambot_dtos.models.list_operation_results_200_response_results_inner.listOperationResults_200_response_results_inner(
                        id = 'result-001', 
                        operation_id = '', 
                        camera_id = 'cam01', 
                        camera_group_id = '', 
                        prompt_id = '', 
                        frame_ref_id = 'frame-ref-abc', 
                        frame_url = '/camera-system/cameras/cam01/frames/frame-cam01-00000001-idx-000000/image', 
                        include = True, 
                        prompt_match_score = 0, 
                        operator_priority_score = 0, 
                        recommended_action = 'Send maintenance to salt the entrance walkway.', 
                        reason = 'The snapshot appears to show a slick surface near the doorway.', 
                        raw_model_json = { }, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ListOperationResults200Response(
                results = [
                    cambot_dtos.models.list_operation_results_200_response_results_inner.listOperationResults_200_response_results_inner(
                        id = 'result-001', 
                        operation_id = '', 
                        camera_id = 'cam01', 
                        camera_group_id = '', 
                        prompt_id = '', 
                        frame_ref_id = 'frame-ref-abc', 
                        frame_url = '/camera-system/cameras/cam01/frames/frame-cam01-00000001-idx-000000/image', 
                        include = True, 
                        prompt_match_score = 0, 
                        operator_priority_score = 0, 
                        recommended_action = 'Send maintenance to salt the entrance walkway.', 
                        reason = 'The snapshot appears to show a slick surface near the doorway.', 
                        raw_model_json = { }, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testListOperationResults200Response(self):
        """Test ListOperationResults200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
