# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.list_operation_second_pass_results200_response import ListOperationSecondPassResults200Response

class TestListOperationSecondPassResults200Response(unittest.TestCase):
    """ListOperationSecondPassResults200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListOperationSecondPassResults200Response:
        """Test ListOperationSecondPassResults200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListOperationSecondPassResults200Response`
        """
        model = ListOperationSecondPassResults200Response()
        if include_optional:
            return ListOperationSecondPassResults200Response(
                results = [
                    cambot_dtos.models.list_operation_second_pass_results_200_response_results_inner.listOperationSecondPassResults_200_response_results_inner(
                        id = 'second-pass-result-001', 
                        operation_id = '', 
                        camera_id = 'cam01', 
                        camera_group_id = '', 
                        prompt_id = '', 
                        first_pass_result_id = '', 
                        frame_ref_id = '', 
                        frame_url = '', 
                        include = True, 
                        global_rank = 56, 
                        prompt_score = 0, 
                        operator_priority_score = 0, 
                        operator_action = 'Inspect this camera first.', 
                        reason = 'This camera is the strongest match after comparing all first-pass results.', 
                        raw_model_json = { }, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ListOperationSecondPassResults200Response(
                results = [
                    cambot_dtos.models.list_operation_second_pass_results_200_response_results_inner.listOperationSecondPassResults_200_response_results_inner(
                        id = 'second-pass-result-001', 
                        operation_id = '', 
                        camera_id = 'cam01', 
                        camera_group_id = '', 
                        prompt_id = '', 
                        first_pass_result_id = '', 
                        frame_ref_id = '', 
                        frame_url = '', 
                        include = True, 
                        global_rank = 56, 
                        prompt_score = 0, 
                        operator_priority_score = 0, 
                        operator_action = 'Inspect this camera first.', 
                        reason = 'This camera is the strongest match after comparing all first-pass results.', 
                        raw_model_json = { }, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testListOperationSecondPassResults200Response(self):
        """Test ListOperationSecondPassResults200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
