# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.api.operations_api import OperationsApi


class TestOperationsApi(unittest.TestCase):
    """OperationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OperationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_operation(self) -> None:
        """Test case for create_operation

        Create a prompt scan operation
        """
        pass

    def test_estimate_operation(self) -> None:
        """Test case for estimate_operation

        Estimate prompt scan usage and cost
        """
        pass

    def test_get_operation(self) -> None:
        """Test case for get_operation

        Get a prompt scan operation
        """
        pass

    def test_list_latest_first_pass_results(self) -> None:
        """Test case for list_latest_first_pass_results

        List latest first-pass results for a prompt and camera group
        """
        pass

    def test_list_latest_second_pass_results(self) -> None:
        """Test case for list_latest_second_pass_results

        List latest second-pass global results for a prompt and camera group
        """
        pass

    def test_list_operation_first_pass_results(self) -> None:
        """Test case for list_operation_first_pass_results

        List first-pass image results for an operation
        """
        pass

    def test_list_operation_second_pass_results(self) -> None:
        """Test case for list_operation_second_pass_results

        List second-pass global prompt results for an operation
        """
        pass

    def test_list_operations(self) -> None:
        """Test case for list_operations

        List prompt scan operations
        """
        pass


if __name__ == '__main__':
    unittest.main()
