# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.update_usage_limit_settings_request import UpdateUsageLimitSettingsRequest

class TestUpdateUsageLimitSettingsRequest(unittest.TestCase):
    """UpdateUsageLimitSettingsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUsageLimitSettingsRequest:
        """Test UpdateUsageLimitSettingsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUsageLimitSettingsRequest`
        """
        model = UpdateUsageLimitSettingsRequest()
        if include_optional:
            return UpdateUsageLimitSettingsRequest(
                max_scans_per_day = 56,
                max_scans_per_month = 56,
                max_estimated_cost_per_day = 1.337,
                max_estimated_cost_per_month = 1.337,
                block_operations_when_limit_reached = True
            )
        else:
            return UpdateUsageLimitSettingsRequest(
        )
        """

    def testUpdateUsageLimitSettingsRequest(self):
        """Test UpdateUsageLimitSettingsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
