# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.update_camera_group_prompt_binding_request import UpdateCameraGroupPromptBindingRequest

class TestUpdateCameraGroupPromptBindingRequest(unittest.TestCase):
    """UpdateCameraGroupPromptBindingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCameraGroupPromptBindingRequest:
        """Test UpdateCameraGroupPromptBindingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCameraGroupPromptBindingRequest`
        """
        model = UpdateCameraGroupPromptBindingRequest()
        if include_optional:
            return UpdateCameraGroupPromptBindingRequest(
                enabled = True,
                scan_frequency = 'manual',
                priority_override = 'low',
                max_estimated_cost_override = 1.337
            )
        else:
            return UpdateCameraGroupPromptBindingRequest(
        )
        """

    def testUpdateCameraGroupPromptBindingRequest(self):
        """Test UpdateCameraGroupPromptBindingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
