# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.list_camera_groups200_response_groups_inner import ListCameraGroups200ResponseGroupsInner

class TestListCameraGroups200ResponseGroupsInner(unittest.TestCase):
    """ListCameraGroups200ResponseGroupsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCameraGroups200ResponseGroupsInner:
        """Test ListCameraGroups200ResponseGroupsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCameraGroups200ResponseGroupsInner`
        """
        model = ListCameraGroups200ResponseGroupsInner()
        if include_optional:
            return ListCameraGroups200ResponseGroupsInner(
                id = 'group-main-entrances',
                name = 'Main Entrances',
                description = 'Operational group for all main entrance cameras.',
                camera_ids = [camera-main-entrance-01, camera-main-entrance-02],
                stats = cambot_dtos.models.list_camera_groups_200_response_groups_inner_stats.listCameraGroups_200_response_groups_inner_stats(
                    camera_count = 12, 
                    applied_prompt_count = 4, 
                    enabled_prompt_count = 3, 
                    scans_per_day = 48, 
                    estimated_cost_per_scan = 0.08, 
                    estimated_cost_per_day = 3.84, 
                    estimated_cost_per_month = 115.2, 
                    last_scanned_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ListCameraGroups200ResponseGroupsInner(
                id = 'group-main-entrances',
                name = 'Main Entrances',
                camera_ids = [camera-main-entrance-01, camera-main-entrance-02],
        )
        """

    def testListCameraGroups200ResponseGroupsInner(self):
        """Test ListCameraGroups200ResponseGroupsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
