# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.list_camera_groups200_response_groups_inner_stats import ListCameraGroups200ResponseGroupsInnerStats

class TestListCameraGroups200ResponseGroupsInnerStats(unittest.TestCase):
    """ListCameraGroups200ResponseGroupsInnerStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCameraGroups200ResponseGroupsInnerStats:
        """Test ListCameraGroups200ResponseGroupsInnerStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCameraGroups200ResponseGroupsInnerStats`
        """
        model = ListCameraGroups200ResponseGroupsInnerStats()
        if include_optional:
            return ListCameraGroups200ResponseGroupsInnerStats(
                camera_count = 12,
                applied_prompt_count = 4,
                enabled_prompt_count = 3,
                scans_per_day = 48,
                estimated_cost_per_scan = 0.08,
                estimated_cost_per_day = 3.84,
                estimated_cost_per_month = 115.2,
                last_scanned_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ListCameraGroups200ResponseGroupsInnerStats(
        )
        """

    def testListCameraGroups200ResponseGroupsInnerStats(self):
        """Test ListCameraGroups200ResponseGroupsInnerStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
