# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.api.camera_system_proxy_api import CameraSystemProxyApi


class TestCameraSystemProxyApi(unittest.TestCase):
    """CameraSystemProxyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CameraSystemProxyApi()

    def tearDown(self) -> None:
        pass

    def test_get_proxied_camera_frame_image(self) -> None:
        """Test case for get_proxied_camera_frame_image

        Proxy camera frame image bytes
        """
        pass

    def test_get_proxied_camera_frame_url(self) -> None:
        """Test case for get_proxied_camera_frame_url

        Proxy camera frame URL
        """
        pass

    def test_get_proxied_camera_snapshot(self) -> None:
        """Test case for get_proxied_camera_snapshot

        Proxy camera snapshot metadata
        """
        pass

    def test_get_proxied_camera_stream(self) -> None:
        """Test case for get_proxied_camera_stream

        Proxy camera stream descriptor
        """
        pass

    def test_get_proxied_camera_system_status(self) -> None:
        """Test case for get_proxied_camera_system_status

        Proxy camera system status
        """
        pass

    def test_get_proxied_integrator_camera(self) -> None:
        """Test case for get_proxied_integrator_camera

        Proxy source camera details
        """
        pass

    def test_get_proxied_integrator_camera_group(self) -> None:
        """Test case for get_proxied_integrator_camera_group

        Proxy source camera group details
        """
        pass

    def test_list_proxied_integrator_camera_group_cameras(self) -> None:
        """Test case for list_proxied_integrator_camera_group_cameras

        Proxy source cameras in a group
        """
        pass

    def test_list_proxied_integrator_camera_groups(self) -> None:
        """Test case for list_proxied_integrator_camera_groups

        Proxy source camera group list
        """
        pass

    def test_list_proxied_integrator_cameras(self) -> None:
        """Test case for list_proxied_integrator_cameras

        Proxy source camera list
        """
        pass


if __name__ == '__main__':
    unittest.main()
