# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.replace_camera_group_cameras_request import ReplaceCameraGroupCamerasRequest

class TestReplaceCameraGroupCamerasRequest(unittest.TestCase):
    """ReplaceCameraGroupCamerasRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReplaceCameraGroupCamerasRequest:
        """Test ReplaceCameraGroupCamerasRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReplaceCameraGroupCamerasRequest`
        """
        model = ReplaceCameraGroupCamerasRequest()
        if include_optional:
            return ReplaceCameraGroupCamerasRequest(
                camera_ids = [
                    ''
                    ]
            )
        else:
            return ReplaceCameraGroupCamerasRequest(
                camera_ids = [
                    ''
                    ],
        )
        """

    def testReplaceCameraGroupCamerasRequest(self):
        """Test ReplaceCameraGroupCamerasRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
