# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.estimate_operation_request_target import EstimateOperationRequestTarget

class TestEstimateOperationRequestTarget(unittest.TestCase):
    """EstimateOperationRequestTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EstimateOperationRequestTarget:
        """Test EstimateOperationRequestTarget
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EstimateOperationRequestTarget`
        """
        model = EstimateOperationRequestTarget()
        if include_optional:
            return EstimateOperationRequestTarget(
                type = 'camera',
                camera_id = '',
                camera_group_id = ''
            )
        else:
            return EstimateOperationRequestTarget(
                type = 'camera',
        )
        """

    def testEstimateOperationRequestTarget(self):
        """Test EstimateOperationRequestTarget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
