FROM docker.io/nginx:alpine

COPY index.html /usr/share/nginx/html/index.html
COPY main.js /usr/share/nginx/html/main.js
COPY styles.css /usr/share/nginx/html/styles.css
COPY dtos /usr/share/nginx/html/dtos

EXPOSE 80
