# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cambot_dtos.models.list_operator_queue_items200_response_items_inner_action import ListOperatorQueueItems200ResponseItemsInnerAction
from cambot_dtos.models.list_operator_queue_items200_response_items_inner_score import ListOperatorQueueItems200ResponseItemsInnerScore
from typing import Optional, Set
from typing_extensions import Self

class ListOperatorQueueItems200ResponseItemsInner(BaseModel):
    """
    ListOperatorQueueItems200ResponseItemsInner
    """ # noqa: E501
    id: StrictStr
    operation_id: Optional[StrictStr] = Field(default=None, alias="operationId")
    camera_id: StrictStr = Field(alias="cameraId")
    camera_group_id: StrictStr = Field(alias="cameraGroupId")
    saved_prompt_id: Optional[StrictStr] = Field(default=None, alias="savedPromptId")
    action: ListOperatorQueueItems200ResponseItemsInnerAction
    score: ListOperatorQueueItems200ResponseItemsInnerScore
    status: StrictStr
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "operationId", "cameraId", "cameraGroupId", "savedPromptId", "action", "score", "status", "createdAt", "updatedAt"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'acknowledged', 'dismissed', 'completed']):
            raise ValueError("must be one of enum values ('pending', 'acknowledged', 'dismissed', 'completed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListOperatorQueueItems200ResponseItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of action
        if self.action:
            _dict['action'] = self.action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of score
        if self.score:
            _dict['score'] = self.score.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListOperatorQueueItems200ResponseItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "operationId": obj.get("operationId"),
            "cameraId": obj.get("cameraId"),
            "cameraGroupId": obj.get("cameraGroupId"),
            "savedPromptId": obj.get("savedPromptId"),
            "action": ListOperatorQueueItems200ResponseItemsInnerAction.from_dict(obj["action"]) if obj.get("action") is not None else None,
            "score": ListOperatorQueueItems200ResponseItemsInnerScore.from_dict(obj["score"]) if obj.get("score") is not None else None,
            "status": obj.get("status"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


