/**
 * Camera System Integrator API
 * Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ListIntegratorCameras200Response from '../model/ListIntegratorCameras200Response';
import ListIntegratorCameras200ResponseCamerasInner from '../model/ListIntegratorCameras200ResponseCamerasInner';

/**
* Cameras service.
* @module api/CamerasApi
* @version 0.1.0
*/
export default class CamerasApi {

    /**
    * Constructs a new CamerasApi. 
    * @alias module:api/CamerasApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get camera details from the camera system
     * @param {String} cameraId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListIntegratorCameras200ResponseCamerasInner} and HTTP response
     */
    getIntegratorCameraWithHttpInfo(cameraId) {
      let postBody = null;
      // verify the required parameter 'cameraId' is set
      if (cameraId === undefined || cameraId === null) {
        throw new Error("Missing the required parameter 'cameraId' when calling getIntegratorCamera");
      }

      let pathParams = {
        'cameraId': cameraId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListIntegratorCameras200ResponseCamerasInner;
      return this.apiClient.callApi(
        '/cameras/{cameraId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get camera details from the camera system
     * @param {String} cameraId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListIntegratorCameras200ResponseCamerasInner}
     */
    getIntegratorCamera(cameraId) {
      return this.getIntegratorCameraWithHttpInfo(cameraId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List cameras from the camera system
     * @param {Object} opts Optional parameters
     * @param {String} [groupId] 
     * @param {String} [search] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListIntegratorCameras200Response} and HTTP response
     */
    listIntegratorCamerasWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'groupId': opts['groupId'],
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListIntegratorCameras200Response;
      return this.apiClient.callApi(
        '/cameras', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List cameras from the camera system
     * @param {Object} opts Optional parameters
     * @param {String} opts.groupId 
     * @param {String} opts.search 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListIntegratorCameras200Response}
     */
    listIntegratorCameras(opts) {
      return this.listIntegratorCamerasWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
