# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: saved_prompts.sql
from typing import Any, AsyncIterator, Iterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from db import models


CREATE_SAVED_PROMPT = """-- name: create_saved_prompt \\:one
INSERT INTO saved_prompts (
  id,
  name,
  description,
  prompt_text,
  enabled
)
VALUES (
  COALESCE(NULLIF(:p1, ''), gen_random_uuid()\\:\\:text),
  :p2,
  :p3,
  :p4,
  COALESCE(:p5, true)
)
RETURNING id, name, description, prompt_text, enabled, created_at, updated_at
"""


DELETE_SAVED_PROMPT = """-- name: delete_saved_prompt \\:exec
DELETE FROM saved_prompts
WHERE id = :p1
"""


GET_SAVED_PROMPT = """-- name: get_saved_prompt \\:one
SELECT id, name, description, prompt_text, enabled, created_at, updated_at
FROM saved_prompts
WHERE id = :p1
"""


LIST_SAVED_PROMPTS = """-- name: list_saved_prompts \\:many
SELECT id, name, description, prompt_text, enabled, created_at, updated_at
FROM saved_prompts
ORDER BY created_at DESC
"""


UPDATE_SAVED_PROMPT = """-- name: update_saved_prompt \\:one
UPDATE saved_prompts
SET
  name = COALESCE(:p1, name),
  description = COALESCE(:p2, description),
  prompt_text = COALESCE(:p3, prompt_text),
  enabled = COALESCE(:p4, enabled)
WHERE id = :p5
RETURNING id, name, description, prompt_text, enabled, created_at, updated_at
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_saved_prompt(self, *, id: Optional[Any], name: str, description: Optional[str], prompt_text: str, enabled: Optional[Any]) -> Optional[models.SavedPrompt]:
        row = self._conn.execute(sqlalchemy.text(CREATE_SAVED_PROMPT), {
            "p1": id,
            "p2": name,
            "p3": description,
            "p4": prompt_text,
            "p5": enabled,
        }).first()
        if row is None:
            return None
        return models.SavedPrompt(
            id=row[0],
            name=row[1],
            description=row[2],
            prompt_text=row[3],
            enabled=row[4],
            created_at=row[5],
            updated_at=row[6],
        )

    def delete_saved_prompt(self, *, id: str) -> None:
        self._conn.execute(sqlalchemy.text(DELETE_SAVED_PROMPT), {"p1": id})

    def get_saved_prompt(self, *, id: str) -> Optional[models.SavedPrompt]:
        row = self._conn.execute(sqlalchemy.text(GET_SAVED_PROMPT), {"p1": id}).first()
        if row is None:
            return None
        return models.SavedPrompt(
            id=row[0],
            name=row[1],
            description=row[2],
            prompt_text=row[3],
            enabled=row[4],
            created_at=row[5],
            updated_at=row[6],
        )

    def list_saved_prompts(self) -> Iterator[models.SavedPrompt]:
        result = self._conn.execute(sqlalchemy.text(LIST_SAVED_PROMPTS))
        for row in result:
            yield models.SavedPrompt(
                id=row[0],
                name=row[1],
                description=row[2],
                prompt_text=row[3],
                enabled=row[4],
                created_at=row[5],
                updated_at=row[6],
            )

    def update_saved_prompt(self, *, name: str, description: Optional[str], prompt_text: str, enabled: bool, id: str) -> Optional[models.SavedPrompt]:
        row = self._conn.execute(sqlalchemy.text(UPDATE_SAVED_PROMPT), {
            "p1": name,
            "p2": description,
            "p3": prompt_text,
            "p4": enabled,
            "p5": id,
        }).first()
        if row is None:
            return None
        return models.SavedPrompt(
            id=row[0],
            name=row[1],
            description=row[2],
            prompt_text=row[3],
            enabled=row[4],
            created_at=row[5],
            updated_at=row[6],
        )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_saved_prompt(self, *, id: Optional[Any], name: str, description: Optional[str], prompt_text: str, enabled: Optional[Any]) -> Optional[models.SavedPrompt]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_SAVED_PROMPT), {
            "p1": id,
            "p2": name,
            "p3": description,
            "p4": prompt_text,
            "p5": enabled,
        })).first()
        if row is None:
            return None
        return models.SavedPrompt(
            id=row[0],
            name=row[1],
            description=row[2],
            prompt_text=row[3],
            enabled=row[4],
            created_at=row[5],
            updated_at=row[6],
        )

    async def delete_saved_prompt(self, *, id: str) -> None:
        await self._conn.execute(sqlalchemy.text(DELETE_SAVED_PROMPT), {"p1": id})

    async def get_saved_prompt(self, *, id: str) -> Optional[models.SavedPrompt]:
        row = (await self._conn.execute(sqlalchemy.text(GET_SAVED_PROMPT), {"p1": id})).first()
        if row is None:
            return None
        return models.SavedPrompt(
            id=row[0],
            name=row[1],
            description=row[2],
            prompt_text=row[3],
            enabled=row[4],
            created_at=row[5],
            updated_at=row[6],
        )

    async def list_saved_prompts(self) -> AsyncIterator[models.SavedPrompt]:
        result = await self._conn.stream(sqlalchemy.text(LIST_SAVED_PROMPTS))
        async for row in result:
            yield models.SavedPrompt(
                id=row[0],
                name=row[1],
                description=row[2],
                prompt_text=row[3],
                enabled=row[4],
                created_at=row[5],
                updated_at=row[6],
            )

    async def update_saved_prompt(self, *, name: str, description: Optional[str], prompt_text: str, enabled: bool, id: str) -> Optional[models.SavedPrompt]:
        row = (await self._conn.execute(sqlalchemy.text(UPDATE_SAVED_PROMPT), {
            "p1": name,
            "p2": description,
            "p3": prompt_text,
            "p4": enabled,
            "p5": id,
        })).first()
        if row is None:
            return None
        return models.SavedPrompt(
            id=row[0],
            name=row[1],
            description=row[2],
            prompt_text=row[3],
            enabled=row[4],
            created_at=row[5],
            updated_at=row[6],
        )
