/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CambotApi);
  }
}(this, function(expect, CambotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CambotApi.ListCameraGroups200ResponseGroupsInnerStats();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListCameraGroups200ResponseGroupsInnerStats', function() {
    it('should create an instance of ListCameraGroups200ResponseGroupsInnerStats', function() {
      // uncomment below and update the code to test ListCameraGroups200ResponseGroupsInnerStats
      //var instance = new CambotApi.ListCameraGroups200ResponseGroupsInnerStats();
      //expect(instance).to.be.a(CambotApi.ListCameraGroups200ResponseGroupsInnerStats);
    });

    it('should have the property cameraCount (base name: "cameraCount")', function() {
      // uncomment below and update the code to test the property cameraCount
      //var instance = new CambotApi.ListCameraGroups200ResponseGroupsInnerStats();
      //expect(instance).to.be();
    });

    it('should have the property appliedPromptCount (base name: "appliedPromptCount")', function() {
      // uncomment below and update the code to test the property appliedPromptCount
      //var instance = new CambotApi.ListCameraGroups200ResponseGroupsInnerStats();
      //expect(instance).to.be();
    });

    it('should have the property enabledPromptCount (base name: "enabledPromptCount")', function() {
      // uncomment below and update the code to test the property enabledPromptCount
      //var instance = new CambotApi.ListCameraGroups200ResponseGroupsInnerStats();
      //expect(instance).to.be();
    });

    it('should have the property scansPerDay (base name: "scansPerDay")', function() {
      // uncomment below and update the code to test the property scansPerDay
      //var instance = new CambotApi.ListCameraGroups200ResponseGroupsInnerStats();
      //expect(instance).to.be();
    });

    it('should have the property estimatedCostPerScan (base name: "estimatedCostPerScan")', function() {
      // uncomment below and update the code to test the property estimatedCostPerScan
      //var instance = new CambotApi.ListCameraGroups200ResponseGroupsInnerStats();
      //expect(instance).to.be();
    });

    it('should have the property estimatedCostPerDay (base name: "estimatedCostPerDay")', function() {
      // uncomment below and update the code to test the property estimatedCostPerDay
      //var instance = new CambotApi.ListCameraGroups200ResponseGroupsInnerStats();
      //expect(instance).to.be();
    });

    it('should have the property estimatedCostPerMonth (base name: "estimatedCostPerMonth")', function() {
      // uncomment below and update the code to test the property estimatedCostPerMonth
      //var instance = new CambotApi.ListCameraGroups200ResponseGroupsInnerStats();
      //expect(instance).to.be();
    });

    it('should have the property lastScannedAt (base name: "lastScannedAt")', function() {
      // uncomment below and update the code to test the property lastScannedAt
      //var instance = new CambotApi.ListCameraGroups200ResponseGroupsInnerStats();
      //expect(instance).to.be();
    });

  });

}));
