FROM docker.io/python:3.12-slim

WORKDIR /app

ENV PYTHONPATH="/app/backend/camera_system_integrator:/app/backend/cambot:${PYTHONPATH}"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY backend ./backend

EXPOSE 8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
