# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.update_gemini_caller_settings_request import UpdateGeminiCallerSettingsRequest

class TestUpdateGeminiCallerSettingsRequest(unittest.TestCase):
    """UpdateGeminiCallerSettingsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateGeminiCallerSettingsRequest:
        """Test UpdateGeminiCallerSettingsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateGeminiCallerSettingsRequest`
        """
        model = UpdateGeminiCallerSettingsRequest()
        if include_optional:
            return UpdateGeminiCallerSettingsRequest(
                enabled = True,
                model_name = '',
                max_requests_per_minute = 56,
                max_tokens_per_request = 56,
                max_cost_per_operation = 1.337,
                max_cost_per_day = 1.337,
                max_cost_per_month = 1.337,
                allow_emergency_override = True
            )
        else:
            return UpdateGeminiCallerSettingsRequest(
        )
        """

    def testUpdateGeminiCallerSettingsRequest(self):
        """Test UpdateGeminiCallerSettingsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
