# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.list_operator_queue_items200_response_items_inner_action import ListOperatorQueueItems200ResponseItemsInnerAction

class TestListOperatorQueueItems200ResponseItemsInnerAction(unittest.TestCase):
    """ListOperatorQueueItems200ResponseItemsInnerAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListOperatorQueueItems200ResponseItemsInnerAction:
        """Test ListOperatorQueueItems200ResponseItemsInnerAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListOperatorQueueItems200ResponseItemsInnerAction`
        """
        model = ListOperatorQueueItems200ResponseItemsInnerAction()
        if include_optional:
            return ListOperatorQueueItems200ResponseItemsInnerAction(
                title = 'Review restricted entrance',
                description = 'A person appears to be standing near the restricted entrance.',
                recommended_action = 'Dispatch operator to verify the entrance area.'
            )
        else:
            return ListOperatorQueueItems200ResponseItemsInnerAction(
                title = 'Review restricted entrance',
                description = 'A person appears to be standing near the restricted entrance.',
        )
        """

    def testListOperatorQueueItems200ResponseItemsInnerAction(self):
        """Test ListOperatorQueueItems200ResponseItemsInnerAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
