# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.list_operations200_response_operations_inner import ListOperations200ResponseOperationsInner

class TestListOperations200ResponseOperationsInner(unittest.TestCase):
    """ListOperations200ResponseOperationsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListOperations200ResponseOperationsInner:
        """Test ListOperations200ResponseOperationsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListOperations200ResponseOperationsInner`
        """
        model = ListOperations200ResponseOperationsInner()
        if include_optional:
            return ListOperations200ResponseOperationsInner(
                id = 'operation-001',
                prompt_id = '',
                camera_group_id = '',
                prompt_binding_id = '',
                trigger = 'manual',
                status = 'queued',
                first_pass_status = 'pending',
                second_pass_status = 'pending',
                total_cameras = 50,
                processed_cameras = 12,
                first_pass_result_count = 12,
                second_pass_result_count = 12,
                matched_cameras = 3,
                estimated_gemini_calls = 56,
                estimated_token_count = 56,
                estimated_cost = 1.337,
                actual_gemini_calls = 56,
                actual_cost = 1.337,
                error_message = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ListOperations200ResponseOperationsInner(
                id = 'operation-001',
                prompt_id = '',
                camera_group_id = '',
                trigger = 'manual',
                status = 'queued',
                first_pass_status = 'pending',
                second_pass_status = 'pending',
                total_cameras = 50,
                processed_cameras = 12,
                first_pass_result_count = 12,
                second_pass_result_count = 12,
                matched_cameras = 3,
        )
        """

    def testListOperations200ResponseOperationsInner(self):
        """Test ListOperations200ResponseOperationsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
