# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cambot_dtos.models.get_usage_summary200_response import GetUsageSummary200Response

class TestGetUsageSummary200Response(unittest.TestCase):
    """GetUsageSummary200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUsageSummary200Response:
        """Test GetUsageSummary200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUsageSummary200Response`
        """
        model = GetUsageSummary200Response()
        if include_optional:
            return GetUsageSummary200Response(
                scans_today = 72,
                scans_yesterday = 63,
                scans_this_month = 1320,
                estimated_cost_today = 8.64,
                estimated_cost_yesterday = 7.25,
                estimated_cost_this_month = 158.2,
                projected_cost_per_day = 9.1,
                projected_cost_this_month = 281.4,
                remaining_daily_budget = 16.36,
                remaining_monthly_budget = 141.8,
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetUsageSummary200Response(
        )
        """

    def testGetUsageSummary200Response(self):
        """Test GetUsageSummary200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
