const state={base:'/api',auth:null,prompts:[],groups:[]};
function $(id){return document.getElementById(id)}
function authHeader(){return state.auth?{'Authorization':'Basic '+btoa(state.auth.user+':'+state.auth.pass)}:{}}
async function api(path,opts={}){const r=await fetch(state.base+path,{...opts,headers:{'Content-Type':'application/json',...authHeader(),...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
function saveAuth(){localStorage.setItem('cambotAuth',JSON.stringify(state.auth))}function loadAuth(){try{state.auth=JSON.parse(localStorage.getItem('cambotAuth')||'null')}catch{}}
async function login(){state.auth={user:$('username').value,pass:$('password').value};await api('/health');saveAuth();$('login').hidden=true;$('dashboard').hidden=false;await refreshAll()}
async function refreshAll(){await Promise.all([loadPrompts(),loadGroups(),loadSettings(),loadQueue(),loadUsage()]);await loadResults()}
async function loadPrompts(){const d=await api('/saved-prompts');state.prompts=d.prompts||[];$('promptSelect').innerHTML=state.prompts.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');$('promptList').innerHTML=state.prompts.map(p=>`<div class="item"><b>${p.name}</b><p>${p.promptText||''}</p><span class="pill">${p.enabled?'enabled':'disabled'}</span></div>`).join('')}
async function loadGroups(){const d=await api('/camera-groups');state.groups=d.groups||[];$('groupSelect').innerHTML=state.groups.map(g=>`<option value="${g.id}">${g.name} (${(g.cameraIds||[]).length})</option>`).join('')}
async function loadSettings(){const s=await api('/settings/gemini');$('continuousEnabled').checked=!!s.continuousScanEnabled;$('continuousInterval').value=s.continuousScanIntervalSeconds||900;$('geminiDelay').value=s.geminiCallDelayMs||2000;$('maxCostDay').value=s.maxCostPerDay||10}
async function loadUsage(){try{$('usageSummary').textContent=JSON.stringify(await api('/usage/summary'),null,2)}catch(e){$('usageSummary').textContent=e.message}}
async function savePrompt(){await api('/saved-prompts',{method:'POST',body:JSON.stringify({name:$('promptName').value||'Untitled prompt',promptText:$('promptText').value||'',enabled:true})});$('promptName').value='';$('promptText').value='';await loadPrompts()}
async function runScan(){const promptId=$('promptSelect').value,cameraGroupId=$('groupSelect').value;await api('/operations',{method:'POST',body:JSON.stringify({promptId,cameraGroupId,trigger:'manual'})});alert('Queued manual scan. GeminiCaller will process it after current operation.')}
async function bindPrompt(){const promptId=$('promptSelect').value,group=$('groupSelect').value;await api(`/camera-groups/${encodeURIComponent(group)}/prompt-bindings`,{method:'POST',body:JSON.stringify({promptId,enabled:true})});alert('Continuous scan binding enabled.')}
async function loadResults(){const promptId=$('promptSelect').value,group=$('groupSelect').value;if(!promptId||!group){$('resultList').innerHTML='<p class="muted">Select a prompt and camera group.</p>';return}const d=await api(`/prompt-results/latest/second-pass?promptId=${encodeURIComponent(promptId)}&cameraGroupId=${encodeURIComponent(group)}`);const rows=d.results||[];$('resultList').innerHTML=rows.length?rows.map(r=>`<div class="card"><div class="score">${Math.round(r.promptScore||0)}</div><div><span class="pill">${r.cameraId}</span><span class="pill">priority ${Math.round(r.operatorPriorityScore||0)}</span></div><p><b>Action:</b> ${r.operatorAction||''}</p><p class="muted">${r.reason||''}</p>${r.frameUrl?`<img class="thumb" src="${r.frameUrl}">`:''}</div>`).join(''):'<p class="muted">No second-pass results yet.</p>'}
async function loadQueue(){const d=await api('/operator-queue');const items=d.items||[];$('queueList').innerHTML=items.map(i=>`<div class="item"><b>${i.cameraId}</b> <span class="pill">${i.status}</span> <span class="pill">priority ${Math.round(i.operatorPriorityScore||0)}</span><p>${i.operatorAction||''}</p><p class="muted">${i.reason||''}</p></div>`).join('')||'<p class="muted">Queue is empty.</p>'}
async function saveSettings(){await api('/settings/gemini',{method:'PUT',body:JSON.stringify({continuousScanEnabled:$('continuousEnabled').checked,continuousScanIntervalSeconds:Number($('continuousInterval').value),geminiCallDelayMs:Number($('geminiDelay').value),maxCostPerDay:Number($('maxCostDay').value)})});await loadSettings()}
function wire(){$('loginBtn').onclick=()=>login().catch(e=>$('loginMsg').textContent=e.message);$('logoutBtn').onclick=()=>{localStorage.removeItem('cambotAuth');location.reload()};$('savePromptBtn').onclick=()=>savePrompt().catch(alert);$('runBtn').onclick=()=>runScan().catch(alert);$('bindBtn').onclick=()=>bindPrompt().catch(alert);$('refreshResultsBtn').onclick=()=>loadResults().catch(alert);$('refreshQueueBtn').onclick=()=>loadQueue().catch(alert);$('saveSettingsBtn').onclick=()=>saveSettings().catch(alert);$('promptSelect').onchange=()=>loadResults().catch(console.warn);$('groupSelect').onchange=()=>loadResults().catch(console.warn)}
wire();loadAuth();if(state.auth){$('login').hidden=true;$('dashboard').hidden=false;refreshAll().catch(()=>{localStorage.removeItem('cambotAuth');$('login').hidden=false;$('dashboard').hidden=true})}
