/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateCameraGroupPromptBindingRequest model module.
 * @module model/CreateCameraGroupPromptBindingRequest
 * @version 0.1.0
 */
class CreateCameraGroupPromptBindingRequest {
    /**
     * Constructs a new <code>CreateCameraGroupPromptBindingRequest</code>.
     * @alias module:model/CreateCameraGroupPromptBindingRequest
     * @param promptId {String} 
     */
    constructor(promptId) { 
        
        CreateCameraGroupPromptBindingRequest.initialize(this, promptId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, promptId) { 
        obj['promptId'] = promptId;
        obj['enabled'] = true;
    }

    /**
     * Constructs a <code>CreateCameraGroupPromptBindingRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCameraGroupPromptBindingRequest} obj Optional instance to populate.
     * @return {module:model/CreateCameraGroupPromptBindingRequest} The populated <code>CreateCameraGroupPromptBindingRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCameraGroupPromptBindingRequest();

            if (data.hasOwnProperty('promptId')) {
                obj['promptId'] = ApiClient.convertToType(data['promptId'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('scanFrequency')) {
                obj['scanFrequency'] = ApiClient.convertToType(data['scanFrequency'], 'String');
            }
            if (data.hasOwnProperty('priorityOverride')) {
                obj['priorityOverride'] = ApiClient.convertToType(data['priorityOverride'], 'String');
            }
            if (data.hasOwnProperty('maxEstimatedCostOverride')) {
                obj['maxEstimatedCostOverride'] = ApiClient.convertToType(data['maxEstimatedCostOverride'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateCameraGroupPromptBindingRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateCameraGroupPromptBindingRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateCameraGroupPromptBindingRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['promptId'] && !(typeof data['promptId'] === 'string' || data['promptId'] instanceof String)) {
            throw new Error("Expected the field `promptId` to be a primitive type in the JSON string but got " + data['promptId']);
        }
        // ensure the json data is a string
        if (data['scanFrequency'] && !(typeof data['scanFrequency'] === 'string' || data['scanFrequency'] instanceof String)) {
            throw new Error("Expected the field `scanFrequency` to be a primitive type in the JSON string but got " + data['scanFrequency']);
        }
        // ensure the json data is a string
        if (data['priorityOverride'] && !(typeof data['priorityOverride'] === 'string' || data['priorityOverride'] instanceof String)) {
            throw new Error("Expected the field `priorityOverride` to be a primitive type in the JSON string but got " + data['priorityOverride']);
        }

        return true;
    }


}

CreateCameraGroupPromptBindingRequest.RequiredProperties = ["promptId"];

/**
 * @member {String} promptId
 */
CreateCameraGroupPromptBindingRequest.prototype['promptId'] = undefined;

/**
 * @member {Boolean} enabled
 * @default true
 */
CreateCameraGroupPromptBindingRequest.prototype['enabled'] = true;

/**
 * @member {module:model/CreateCameraGroupPromptBindingRequest.ScanFrequencyEnum} scanFrequency
 */
CreateCameraGroupPromptBindingRequest.prototype['scanFrequency'] = undefined;

/**
 * @member {module:model/CreateCameraGroupPromptBindingRequest.PriorityOverrideEnum} priorityOverride
 */
CreateCameraGroupPromptBindingRequest.prototype['priorityOverride'] = undefined;

/**
 * @member {Number} maxEstimatedCostOverride
 */
CreateCameraGroupPromptBindingRequest.prototype['maxEstimatedCostOverride'] = undefined;





/**
 * Allowed values for the <code>scanFrequency</code> property.
 * @enum {String}
 * @readonly
 */
CreateCameraGroupPromptBindingRequest['ScanFrequencyEnum'] = {

    /**
     * value: "manual"
     * @const
     */
    "manual": "manual",

    /**
     * value: "hourly"
     * @const
     */
    "hourly": "hourly",

    /**
     * value: "daily"
     * @const
     */
    "daily": "daily",

    /**
     * value: "continuous"
     * @const
     */
    "continuous": "continuous"
};


/**
 * Allowed values for the <code>priorityOverride</code> property.
 * @enum {String}
 * @readonly
 */
CreateCameraGroupPromptBindingRequest['PriorityOverrideEnum'] = {

    /**
     * value: "low"
     * @const
     */
    "low": "low",

    /**
     * value: "normal"
     * @const
     */
    "normal": "normal",

    /**
     * value: "high"
     * @const
     */
    "high": "high",

    /**
     * value: "emergency"
     * @const
     */
    "emergency": "emergency"
};



export default CreateCameraGroupPromptBindingRequest;

