/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListCameraGroups200ResponseGroupsInnerStats from './ListCameraGroups200ResponseGroupsInnerStats';

/**
 * The ListCameraGroups200ResponseGroupsInner model module.
 * @module model/ListCameraGroups200ResponseGroupsInner
 * @version 0.1.0
 */
class ListCameraGroups200ResponseGroupsInner {
    /**
     * Constructs a new <code>ListCameraGroups200ResponseGroupsInner</code>.
     * @alias module:model/ListCameraGroups200ResponseGroupsInner
     * @param id {String} 
     * @param name {String} 
     * @param cameraIds {Array.<String>} 
     */
    constructor(id, name, cameraIds) { 
        
        ListCameraGroups200ResponseGroupsInner.initialize(this, id, name, cameraIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, cameraIds) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['cameraIds'] = cameraIds;
    }

    /**
     * Constructs a <code>ListCameraGroups200ResponseGroupsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListCameraGroups200ResponseGroupsInner} obj Optional instance to populate.
     * @return {module:model/ListCameraGroups200ResponseGroupsInner} The populated <code>ListCameraGroups200ResponseGroupsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListCameraGroups200ResponseGroupsInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('cameraIds')) {
                obj['cameraIds'] = ApiClient.convertToType(data['cameraIds'], ['String']);
            }
            if (data.hasOwnProperty('stats')) {
                obj['stats'] = ListCameraGroups200ResponseGroupsInnerStats.constructFromObject(data['stats']);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListCameraGroups200ResponseGroupsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListCameraGroups200ResponseGroupsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListCameraGroups200ResponseGroupsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['cameraIds'])) {
            throw new Error("Expected the field `cameraIds` to be an array in the JSON data but got " + data['cameraIds']);
        }
        // validate the optional field `stats`
        if (data['stats']) { // data not null
          ListCameraGroups200ResponseGroupsInnerStats.validateJSON(data['stats']);
        }

        return true;
    }


}

ListCameraGroups200ResponseGroupsInner.RequiredProperties = ["id", "name", "cameraIds"];

/**
 * @member {String} id
 */
ListCameraGroups200ResponseGroupsInner.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ListCameraGroups200ResponseGroupsInner.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ListCameraGroups200ResponseGroupsInner.prototype['description'] = undefined;

/**
 * @member {Array.<String>} cameraIds
 */
ListCameraGroups200ResponseGroupsInner.prototype['cameraIds'] = undefined;

/**
 * @member {module:model/ListCameraGroups200ResponseGroupsInnerStats} stats
 */
ListCameraGroups200ResponseGroupsInner.prototype['stats'] = undefined;

/**
 * @member {Date} createdAt
 */
ListCameraGroups200ResponseGroupsInner.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
ListCameraGroups200ResponseGroupsInner.prototype['updatedAt'] = undefined;






export default ListCameraGroups200ResponseGroupsInner;

