/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListCameraGroupPromptBindings200ResponseBindingsInner model module.
 * @module model/ListCameraGroupPromptBindings200ResponseBindingsInner
 * @version 0.1.0
 */
class ListCameraGroupPromptBindings200ResponseBindingsInner {
    /**
     * Constructs a new <code>ListCameraGroupPromptBindings200ResponseBindingsInner</code>.
     * @alias module:model/ListCameraGroupPromptBindings200ResponseBindingsInner
     * @param id {String} 
     * @param cameraGroupId {String} 
     * @param promptId {String} 
     * @param enabled {Boolean} 
     */
    constructor(id, cameraGroupId, promptId, enabled) { 
        
        ListCameraGroupPromptBindings200ResponseBindingsInner.initialize(this, id, cameraGroupId, promptId, enabled);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, cameraGroupId, promptId, enabled) { 
        obj['id'] = id;
        obj['cameraGroupId'] = cameraGroupId;
        obj['promptId'] = promptId;
        obj['enabled'] = enabled;
    }

    /**
     * Constructs a <code>ListCameraGroupPromptBindings200ResponseBindingsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListCameraGroupPromptBindings200ResponseBindingsInner} obj Optional instance to populate.
     * @return {module:model/ListCameraGroupPromptBindings200ResponseBindingsInner} The populated <code>ListCameraGroupPromptBindings200ResponseBindingsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListCameraGroupPromptBindings200ResponseBindingsInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('cameraGroupId')) {
                obj['cameraGroupId'] = ApiClient.convertToType(data['cameraGroupId'], 'String');
            }
            if (data.hasOwnProperty('promptId')) {
                obj['promptId'] = ApiClient.convertToType(data['promptId'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('scanFrequency')) {
                obj['scanFrequency'] = ApiClient.convertToType(data['scanFrequency'], 'String');
            }
            if (data.hasOwnProperty('priorityOverride')) {
                obj['priorityOverride'] = ApiClient.convertToType(data['priorityOverride'], 'String');
            }
            if (data.hasOwnProperty('maxEstimatedCostOverride')) {
                obj['maxEstimatedCostOverride'] = ApiClient.convertToType(data['maxEstimatedCostOverride'], 'Number');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListCameraGroupPromptBindings200ResponseBindingsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListCameraGroupPromptBindings200ResponseBindingsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListCameraGroupPromptBindings200ResponseBindingsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['cameraGroupId'] && !(typeof data['cameraGroupId'] === 'string' || data['cameraGroupId'] instanceof String)) {
            throw new Error("Expected the field `cameraGroupId` to be a primitive type in the JSON string but got " + data['cameraGroupId']);
        }
        // ensure the json data is a string
        if (data['promptId'] && !(typeof data['promptId'] === 'string' || data['promptId'] instanceof String)) {
            throw new Error("Expected the field `promptId` to be a primitive type in the JSON string but got " + data['promptId']);
        }
        // ensure the json data is a string
        if (data['scanFrequency'] && !(typeof data['scanFrequency'] === 'string' || data['scanFrequency'] instanceof String)) {
            throw new Error("Expected the field `scanFrequency` to be a primitive type in the JSON string but got " + data['scanFrequency']);
        }
        // ensure the json data is a string
        if (data['priorityOverride'] && !(typeof data['priorityOverride'] === 'string' || data['priorityOverride'] instanceof String)) {
            throw new Error("Expected the field `priorityOverride` to be a primitive type in the JSON string but got " + data['priorityOverride']);
        }

        return true;
    }


}

ListCameraGroupPromptBindings200ResponseBindingsInner.RequiredProperties = ["id", "cameraGroupId", "promptId", "enabled"];

/**
 * @member {String} id
 */
ListCameraGroupPromptBindings200ResponseBindingsInner.prototype['id'] = undefined;

/**
 * @member {String} cameraGroupId
 */
ListCameraGroupPromptBindings200ResponseBindingsInner.prototype['cameraGroupId'] = undefined;

/**
 * @member {String} promptId
 */
ListCameraGroupPromptBindings200ResponseBindingsInner.prototype['promptId'] = undefined;

/**
 * @member {Boolean} enabled
 */
ListCameraGroupPromptBindings200ResponseBindingsInner.prototype['enabled'] = undefined;

/**
 * @member {module:model/ListCameraGroupPromptBindings200ResponseBindingsInner.ScanFrequencyEnum} scanFrequency
 */
ListCameraGroupPromptBindings200ResponseBindingsInner.prototype['scanFrequency'] = undefined;

/**
 * @member {module:model/ListCameraGroupPromptBindings200ResponseBindingsInner.PriorityOverrideEnum} priorityOverride
 */
ListCameraGroupPromptBindings200ResponseBindingsInner.prototype['priorityOverride'] = undefined;

/**
 * @member {Number} maxEstimatedCostOverride
 */
ListCameraGroupPromptBindings200ResponseBindingsInner.prototype['maxEstimatedCostOverride'] = undefined;

/**
 * @member {Date} createdAt
 */
ListCameraGroupPromptBindings200ResponseBindingsInner.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
ListCameraGroupPromptBindings200ResponseBindingsInner.prototype['updatedAt'] = undefined;





/**
 * Allowed values for the <code>scanFrequency</code> property.
 * @enum {String}
 * @readonly
 */
ListCameraGroupPromptBindings200ResponseBindingsInner['ScanFrequencyEnum'] = {

    /**
     * value: "manual"
     * @const
     */
    "manual": "manual",

    /**
     * value: "hourly"
     * @const
     */
    "hourly": "hourly",

    /**
     * value: "daily"
     * @const
     */
    "daily": "daily",

    /**
     * value: "continuous"
     * @const
     */
    "continuous": "continuous"
};


/**
 * Allowed values for the <code>priorityOverride</code> property.
 * @enum {String}
 * @readonly
 */
ListCameraGroupPromptBindings200ResponseBindingsInner['PriorityOverrideEnum'] = {

    /**
     * value: "low"
     * @const
     */
    "low": "low",

    /**
     * value: "normal"
     * @const
     */
    "normal": "normal",

    /**
     * value: "high"
     * @const
     */
    "high": "high",

    /**
     * value: "emergency"
     * @const
     */
    "emergency": "emergency"
};



export default ListCameraGroupPromptBindings200ResponseBindingsInner;

