/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CambotApi);
  }
}(this, function(expect, CambotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CambotApi.GetGeminiCallerSettings200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetGeminiCallerSettings200Response', function() {
    it('should create an instance of GetGeminiCallerSettings200Response', function() {
      // uncomment below and update the code to test GetGeminiCallerSettings200Response
      //var instance = new CambotApi.GetGeminiCallerSettings200Response();
      //expect(instance).to.be.a(CambotApi.GetGeminiCallerSettings200Response);
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instance = new CambotApi.GetGeminiCallerSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property modelName (base name: "modelName")', function() {
      // uncomment below and update the code to test the property modelName
      //var instance = new CambotApi.GetGeminiCallerSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property maxRequestsPerMinute (base name: "maxRequestsPerMinute")', function() {
      // uncomment below and update the code to test the property maxRequestsPerMinute
      //var instance = new CambotApi.GetGeminiCallerSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property maxTokensPerRequest (base name: "maxTokensPerRequest")', function() {
      // uncomment below and update the code to test the property maxTokensPerRequest
      //var instance = new CambotApi.GetGeminiCallerSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property maxCostPerOperation (base name: "maxCostPerOperation")', function() {
      // uncomment below and update the code to test the property maxCostPerOperation
      //var instance = new CambotApi.GetGeminiCallerSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property maxCostPerDay (base name: "maxCostPerDay")', function() {
      // uncomment below and update the code to test the property maxCostPerDay
      //var instance = new CambotApi.GetGeminiCallerSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property maxCostPerMonth (base name: "maxCostPerMonth")', function() {
      // uncomment below and update the code to test the property maxCostPerMonth
      //var instance = new CambotApi.GetGeminiCallerSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property allowEmergencyOverride (base name: "allowEmergencyOverride")', function() {
      // uncomment below and update the code to test the property allowEmergencyOverride
      //var instance = new CambotApi.GetGeminiCallerSettings200Response();
      //expect(instance).to.be();
    });

  });

}));
