/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CambotApi);
  }
}(this, function(expect, CambotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CambotApi.GetProxiedCameraStream200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetProxiedCameraStream200Response', function() {
    it('should create an instance of GetProxiedCameraStream200Response', function() {
      // uncomment below and update the code to test GetProxiedCameraStream200Response
      //var instance = new CambotApi.GetProxiedCameraStream200Response();
      //expect(instance).to.be.a(CambotApi.GetProxiedCameraStream200Response);
    });

    it('should have the property cameraId (base name: "cameraId")', function() {
      // uncomment below and update the code to test the property cameraId
      //var instance = new CambotApi.GetProxiedCameraStream200Response();
      //expect(instance).to.be();
    });

    it('should have the property streamType (base name: "streamType")', function() {
      // uncomment below and update the code to test the property streamType
      //var instance = new CambotApi.GetProxiedCameraStream200Response();
      //expect(instance).to.be();
    });

    it('should have the property streamUrl (base name: "streamUrl")', function() {
      // uncomment below and update the code to test the property streamUrl
      //var instance = new CambotApi.GetProxiedCameraStream200Response();
      //expect(instance).to.be();
    });

    it('should have the property expiresAt (base name: "expiresAt")', function() {
      // uncomment below and update the code to test the property expiresAt
      //var instance = new CambotApi.GetProxiedCameraStream200Response();
      //expect(instance).to.be();
    });

  });

}));
