/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CambotApi);
  }
}(this, function(expect, CambotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CambotApi.GetUsageLimitSettings200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetUsageLimitSettings200Response', function() {
    it('should create an instance of GetUsageLimitSettings200Response', function() {
      // uncomment below and update the code to test GetUsageLimitSettings200Response
      //var instance = new CambotApi.GetUsageLimitSettings200Response();
      //expect(instance).to.be.a(CambotApi.GetUsageLimitSettings200Response);
    });

    it('should have the property maxScansPerDay (base name: "maxScansPerDay")', function() {
      // uncomment below and update the code to test the property maxScansPerDay
      //var instance = new CambotApi.GetUsageLimitSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property maxScansPerMonth (base name: "maxScansPerMonth")', function() {
      // uncomment below and update the code to test the property maxScansPerMonth
      //var instance = new CambotApi.GetUsageLimitSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property maxEstimatedCostPerDay (base name: "maxEstimatedCostPerDay")', function() {
      // uncomment below and update the code to test the property maxEstimatedCostPerDay
      //var instance = new CambotApi.GetUsageLimitSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property maxEstimatedCostPerMonth (base name: "maxEstimatedCostPerMonth")', function() {
      // uncomment below and update the code to test the property maxEstimatedCostPerMonth
      //var instance = new CambotApi.GetUsageLimitSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property blockOperationsWhenLimitReached (base name: "blockOperationsWhenLimitReached")', function() {
      // uncomment below and update the code to test the property blockOperationsWhenLimitReached
      //var instance = new CambotApi.GetUsageLimitSettings200Response();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new CambotApi.GetUsageLimitSettings200Response();
      //expect(instance).to.be();
    });

  });

}));
