/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CambotApi);
  }
}(this, function(expect, CambotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CambotApi.GetUsageSummary200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetUsageSummary200Response', function() {
    it('should create an instance of GetUsageSummary200Response', function() {
      // uncomment below and update the code to test GetUsageSummary200Response
      //var instance = new CambotApi.GetUsageSummary200Response();
      //expect(instance).to.be.a(CambotApi.GetUsageSummary200Response);
    });

    it('should have the property scansToday (base name: "scansToday")', function() {
      // uncomment below and update the code to test the property scansToday
      //var instance = new CambotApi.GetUsageSummary200Response();
      //expect(instance).to.be();
    });

    it('should have the property scansThisMonth (base name: "scansThisMonth")', function() {
      // uncomment below and update the code to test the property scansThisMonth
      //var instance = new CambotApi.GetUsageSummary200Response();
      //expect(instance).to.be();
    });

    it('should have the property estimatedCostToday (base name: "estimatedCostToday")', function() {
      // uncomment below and update the code to test the property estimatedCostToday
      //var instance = new CambotApi.GetUsageSummary200Response();
      //expect(instance).to.be();
    });

    it('should have the property estimatedCostThisMonth (base name: "estimatedCostThisMonth")', function() {
      // uncomment below and update the code to test the property estimatedCostThisMonth
      //var instance = new CambotApi.GetUsageSummary200Response();
      //expect(instance).to.be();
    });

    it('should have the property remainingDailyBudget (base name: "remainingDailyBudget")', function() {
      // uncomment below and update the code to test the property remainingDailyBudget
      //var instance = new CambotApi.GetUsageSummary200Response();
      //expect(instance).to.be();
    });

    it('should have the property remainingMonthlyBudget (base name: "remainingMonthlyBudget")', function() {
      // uncomment below and update the code to test the property remainingMonthlyBudget
      //var instance = new CambotApi.GetUsageSummary200Response();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdatedAt (base name: "lastUpdatedAt")', function() {
      // uncomment below and update the code to test the property lastUpdatedAt
      //var instance = new CambotApi.GetUsageSummary200Response();
      //expect(instance).to.be();
    });

  });

}));
