/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CambotApi);
  }
}(this, function(expect, CambotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListOperatorQueueItems200ResponseItemsInner', function() {
    it('should create an instance of ListOperatorQueueItems200ResponseItemsInner', function() {
      // uncomment below and update the code to test ListOperatorQueueItems200ResponseItemsInner
      //var instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
      //expect(instance).to.be.a(CambotApi.ListOperatorQueueItems200ResponseItemsInner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property operationId (base name: "operationId")', function() {
      // uncomment below and update the code to test the property operationId
      //var instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property cameraId (base name: "cameraId")', function() {
      // uncomment below and update the code to test the property cameraId
      //var instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property cameraGroupId (base name: "cameraGroupId")', function() {
      // uncomment below and update the code to test the property cameraGroupId
      //var instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property savedPromptId (base name: "savedPromptId")', function() {
      // uncomment below and update the code to test the property savedPromptId
      //var instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property action (base name: "action")', function() {
      // uncomment below and update the code to test the property action
      //var instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new CambotApi.ListOperatorQueueItems200ResponseItemsInner();
      //expect(instance).to.be();
    });

  });

}));
