/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CambotApi);
  }
}(this, function(expect, CambotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CambotApi.ListOperations200ResponseOperationsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListOperations200ResponseOperationsInner', function() {
    it('should create an instance of ListOperations200ResponseOperationsInner', function() {
      // uncomment below and update the code to test ListOperations200ResponseOperationsInner
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be.a(CambotApi.ListOperations200ResponseOperationsInner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property promptId (base name: "promptId")', function() {
      // uncomment below and update the code to test the property promptId
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property cameraGroupId (base name: "cameraGroupId")', function() {
      // uncomment below and update the code to test the property cameraGroupId
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property promptBindingId (base name: "promptBindingId")', function() {
      // uncomment below and update the code to test the property promptBindingId
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property trigger (base name: "trigger")', function() {
      // uncomment below and update the code to test the property trigger
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property firstPassStatus (base name: "firstPassStatus")', function() {
      // uncomment below and update the code to test the property firstPassStatus
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property secondPassStatus (base name: "secondPassStatus")', function() {
      // uncomment below and update the code to test the property secondPassStatus
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property totalCameras (base name: "totalCameras")', function() {
      // uncomment below and update the code to test the property totalCameras
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property processedCameras (base name: "processedCameras")', function() {
      // uncomment below and update the code to test the property processedCameras
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property firstPassResultCount (base name: "firstPassResultCount")', function() {
      // uncomment below and update the code to test the property firstPassResultCount
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property secondPassResultCount (base name: "secondPassResultCount")', function() {
      // uncomment below and update the code to test the property secondPassResultCount
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property matchedCameras (base name: "matchedCameras")', function() {
      // uncomment below and update the code to test the property matchedCameras
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property estimatedGeminiCalls (base name: "estimatedGeminiCalls")', function() {
      // uncomment below and update the code to test the property estimatedGeminiCalls
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property estimatedTokenCount (base name: "estimatedTokenCount")', function() {
      // uncomment below and update the code to test the property estimatedTokenCount
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property estimatedCost (base name: "estimatedCost")', function() {
      // uncomment below and update the code to test the property estimatedCost
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property actualGeminiCalls (base name: "actualGeminiCalls")', function() {
      // uncomment below and update the code to test the property actualGeminiCalls
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property actualCost (base name: "actualCost")', function() {
      // uncomment below and update the code to test the property actualCost
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "errorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property startedAt (base name: "startedAt")', function() {
      // uncomment below and update the code to test the property startedAt
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

    it('should have the property completedAt (base name: "completedAt")', function() {
      // uncomment below and update the code to test the property completedAt
      //var instance = new CambotApi.ListOperations200ResponseOperationsInner();
      //expect(instance).to.be();
    });

  });

}));
