/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CambotApi);
  }
}(this, function(expect, CambotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CambotApi.UpdateCameraGroupPromptBindingRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateCameraGroupPromptBindingRequest', function() {
    it('should create an instance of UpdateCameraGroupPromptBindingRequest', function() {
      // uncomment below and update the code to test UpdateCameraGroupPromptBindingRequest
      //var instance = new CambotApi.UpdateCameraGroupPromptBindingRequest();
      //expect(instance).to.be.a(CambotApi.UpdateCameraGroupPromptBindingRequest);
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instance = new CambotApi.UpdateCameraGroupPromptBindingRequest();
      //expect(instance).to.be();
    });

    it('should have the property scanFrequency (base name: "scanFrequency")', function() {
      // uncomment below and update the code to test the property scanFrequency
      //var instance = new CambotApi.UpdateCameraGroupPromptBindingRequest();
      //expect(instance).to.be();
    });

    it('should have the property priorityOverride (base name: "priorityOverride")', function() {
      // uncomment below and update the code to test the property priorityOverride
      //var instance = new CambotApi.UpdateCameraGroupPromptBindingRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxEstimatedCostOverride (base name: "maxEstimatedCostOverride")', function() {
      // uncomment below and update the code to test the property maxEstimatedCostOverride
      //var instance = new CambotApi.UpdateCameraGroupPromptBindingRequest();
      //expect(instance).to.be();
    });

  });

}));
