/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateSavedPromptRequest from '../model/CreateSavedPromptRequest';
import ListSavedPrompts200Response from '../model/ListSavedPrompts200Response';
import ListSavedPrompts200ResponsePromptsInner from '../model/ListSavedPrompts200ResponsePromptsInner';
import UpdateSavedPromptRequest from '../model/UpdateSavedPromptRequest';

/**
* SavedPrompts service.
* @module api/SavedPromptsApi
* @version 0.1.0
*/
export default class SavedPromptsApi {

    /**
    * Constructs a new SavedPromptsApi. 
    * @alias module:api/SavedPromptsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create a saved prompt
     * @param {module:model/CreateSavedPromptRequest} createSavedPromptRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListSavedPrompts200ResponsePromptsInner} and HTTP response
     */
    createSavedPromptWithHttpInfo(createSavedPromptRequest) {
      let postBody = createSavedPromptRequest;
      // verify the required parameter 'createSavedPromptRequest' is set
      if (createSavedPromptRequest === undefined || createSavedPromptRequest === null) {
        throw new Error("Missing the required parameter 'createSavedPromptRequest' when calling createSavedPrompt");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ListSavedPrompts200ResponsePromptsInner;
      return this.apiClient.callApi(
        '/saved-prompts', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a saved prompt
     * @param {module:model/CreateSavedPromptRequest} createSavedPromptRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListSavedPrompts200ResponsePromptsInner}
     */
    createSavedPrompt(createSavedPromptRequest) {
      return this.createSavedPromptWithHttpInfo(createSavedPromptRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a saved prompt
     * @param {String} promptId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteSavedPromptWithHttpInfo(promptId) {
      let postBody = null;
      // verify the required parameter 'promptId' is set
      if (promptId === undefined || promptId === null) {
        throw new Error("Missing the required parameter 'promptId' when calling deleteSavedPrompt");
      }

      let pathParams = {
        'promptId': promptId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/saved-prompts/{promptId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete a saved prompt
     * @param {String} promptId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteSavedPrompt(promptId) {
      return this.deleteSavedPromptWithHttpInfo(promptId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a saved prompt
     * @param {String} promptId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListSavedPrompts200ResponsePromptsInner} and HTTP response
     */
    getSavedPromptWithHttpInfo(promptId) {
      let postBody = null;
      // verify the required parameter 'promptId' is set
      if (promptId === undefined || promptId === null) {
        throw new Error("Missing the required parameter 'promptId' when calling getSavedPrompt");
      }

      let pathParams = {
        'promptId': promptId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListSavedPrompts200ResponsePromptsInner;
      return this.apiClient.callApi(
        '/saved-prompts/{promptId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a saved prompt
     * @param {String} promptId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListSavedPrompts200ResponsePromptsInner}
     */
    getSavedPrompt(promptId) {
      return this.getSavedPromptWithHttpInfo(promptId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List saved prompts
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [promptType] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListSavedPrompts200Response} and HTTP response
     */
    listSavedPromptsWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'promptType': opts['promptType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListSavedPrompts200Response;
      return this.apiClient.callApi(
        '/saved-prompts', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List saved prompts
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.promptType 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListSavedPrompts200Response}
     */
    listSavedPrompts(opts) {
      return this.listSavedPromptsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update a saved prompt
     * @param {String} promptId 
     * @param {module:model/UpdateSavedPromptRequest} updateSavedPromptRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListSavedPrompts200ResponsePromptsInner} and HTTP response
     */
    updateSavedPromptWithHttpInfo(promptId, updateSavedPromptRequest) {
      let postBody = updateSavedPromptRequest;
      // verify the required parameter 'promptId' is set
      if (promptId === undefined || promptId === null) {
        throw new Error("Missing the required parameter 'promptId' when calling updateSavedPrompt");
      }
      // verify the required parameter 'updateSavedPromptRequest' is set
      if (updateSavedPromptRequest === undefined || updateSavedPromptRequest === null) {
        throw new Error("Missing the required parameter 'updateSavedPromptRequest' when calling updateSavedPrompt");
      }

      let pathParams = {
        'promptId': promptId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ListSavedPrompts200ResponsePromptsInner;
      return this.apiClient.callApi(
        '/saved-prompts/{promptId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update a saved prompt
     * @param {String} promptId 
     * @param {module:model/UpdateSavedPromptRequest} updateSavedPromptRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListSavedPrompts200ResponsePromptsInner}
     */
    updateSavedPrompt(promptId, updateSavedPromptRequest) {
      return this.updateSavedPromptWithHttpInfo(promptId, updateSavedPromptRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
