/**
 * Camera System Integrator API
 * Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CameraSystemIntegratorApi);
  }
}(this, function(expect, CameraSystemIntegratorApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CameraSystemIntegratorApi.ListIntegratorCameras200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListIntegratorCameras200Response', function() {
    it('should create an instance of ListIntegratorCameras200Response', function() {
      // uncomment below and update the code to test ListIntegratorCameras200Response
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200Response();
      //expect(instance).to.be.a(CameraSystemIntegratorApi.ListIntegratorCameras200Response);
    });

    it('should have the property cameras (base name: "cameras")', function() {
      // uncomment below and update the code to test the property cameras
      //var instance = new CameraSystemIntegratorApi.ListIntegratorCameras200Response();
      //expect(instance).to.be();
    });

  });

}));
