# coding: utf-8

"""
    Camera System Integrator API

    Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from camera_system_integrator_dtos.models.list_integrator_camera_groups200_response import ListIntegratorCameraGroups200Response

class TestListIntegratorCameraGroups200Response(unittest.TestCase):
    """ListIntegratorCameraGroups200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListIntegratorCameraGroups200Response:
        """Test ListIntegratorCameraGroups200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListIntegratorCameraGroups200Response`
        """
        model = ListIntegratorCameraGroups200Response()
        if include_optional:
            return ListIntegratorCameraGroups200Response(
                groups = [
                    camera_system_integrator_dtos.models.list_integrator_camera_groups_200_response_groups_inner.listIntegratorCameraGroups_200_response_groups_inner(
                        id = 'source-group-building-a', 
                        name = 'Building A', 
                        description = '', 
                        parent_group_id = '', 
                        camera_ids = [
                            ''
                            ], 
                        child_group_ids = [
                            ''
                            ], 
                        vendor_metadata = { }, )
                    ]
            )
        else:
            return ListIntegratorCameraGroups200Response(
                groups = [
                    camera_system_integrator_dtos.models.list_integrator_camera_groups_200_response_groups_inner.listIntegratorCameraGroups_200_response_groups_inner(
                        id = 'source-group-building-a', 
                        name = 'Building A', 
                        description = '', 
                        parent_group_id = '', 
                        camera_ids = [
                            ''
                            ], 
                        child_group_ids = [
                            ''
                            ], 
                        vendor_metadata = { }, )
                    ],
        )
        """

    def testListIntegratorCameraGroups200Response(self):
        """Test ListIntegratorCameraGroups200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
