# coding: utf-8

"""
    Camera System Integrator API

    Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from camera_system_integrator_dtos.api.snapshots_api import SnapshotsApi


class TestSnapshotsApi(unittest.TestCase):
    """SnapshotsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SnapshotsApi()

    def tearDown(self) -> None:
        pass

    def test_get_camera_snapshot(self) -> None:
        """Test case for get_camera_snapshot

        Get latest camera snapshot
        """
        pass


if __name__ == '__main__':
    unittest.main()
