# coding: utf-8

"""
    Camera System Integrator API

    Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from camera_system_integrator_dtos.api.system_api import SystemApi


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemApi()

    def tearDown(self) -> None:
        pass

    def test_get_camera_system_status(self) -> None:
        """Test case for get_camera_system_status

        Get camera system status
        """
        pass


if __name__ == '__main__':
    unittest.main()
