/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateOperatorQueueItemRequest model module.
 * @module model/CreateOperatorQueueItemRequest
 * @version 0.1.0
 */
class CreateOperatorQueueItemRequest {
    /**
     * Constructs a new <code>CreateOperatorQueueItemRequest</code>.
     * @alias module:model/CreateOperatorQueueItemRequest
     * @param secondPassResultId {String} Creates a queue item from a stored second-pass/global prompt result.
     */
    constructor(secondPassResultId) { 
        
        CreateOperatorQueueItemRequest.initialize(this, secondPassResultId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, secondPassResultId) { 
        obj['secondPassResultId'] = secondPassResultId;
    }

    /**
     * Constructs a <code>CreateOperatorQueueItemRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateOperatorQueueItemRequest} obj Optional instance to populate.
     * @return {module:model/CreateOperatorQueueItemRequest} The populated <code>CreateOperatorQueueItemRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateOperatorQueueItemRequest();

            if (data.hasOwnProperty('secondPassResultId')) {
                obj['secondPassResultId'] = ApiClient.convertToType(data['secondPassResultId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateOperatorQueueItemRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateOperatorQueueItemRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateOperatorQueueItemRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['secondPassResultId'] && !(typeof data['secondPassResultId'] === 'string' || data['secondPassResultId'] instanceof String)) {
            throw new Error("Expected the field `secondPassResultId` to be a primitive type in the JSON string but got " + data['secondPassResultId']);
        }

        return true;
    }


}

CreateOperatorQueueItemRequest.RequiredProperties = ["secondPassResultId"];

/**
 * Creates a queue item from a stored second-pass/global prompt result.
 * @member {String} secondPassResultId
 */
CreateOperatorQueueItemRequest.prototype['secondPassResultId'] = undefined;






export default CreateOperatorQueueItemRequest;

