/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateOperatorQueueItemRequest model module.
 * @module model/CreateOperatorQueueItemRequest
 * @version 0.1.0
 */
class CreateOperatorQueueItemRequest {
    /**
     * Constructs a new <code>CreateOperatorQueueItemRequest</code>.
     * @alias module:model/CreateOperatorQueueItemRequest
     * @param operationResultId {String} Creates a queue item from a stored Gemini operation result.
     */
    constructor(operationResultId) { 
        
        CreateOperatorQueueItemRequest.initialize(this, operationResultId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, operationResultId) { 
        obj['operationResultId'] = operationResultId;
    }

    /**
     * Constructs a <code>CreateOperatorQueueItemRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateOperatorQueueItemRequest} obj Optional instance to populate.
     * @return {module:model/CreateOperatorQueueItemRequest} The populated <code>CreateOperatorQueueItemRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateOperatorQueueItemRequest();

            if (data.hasOwnProperty('operationResultId')) {
                obj['operationResultId'] = ApiClient.convertToType(data['operationResultId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateOperatorQueueItemRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateOperatorQueueItemRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateOperatorQueueItemRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['operationResultId'] && !(typeof data['operationResultId'] === 'string' || data['operationResultId'] instanceof String)) {
            throw new Error("Expected the field `operationResultId` to be a primitive type in the JSON string but got " + data['operationResultId']);
        }

        return true;
    }


}

CreateOperatorQueueItemRequest.RequiredProperties = ["operationResultId"];

/**
 * Creates a queue item from a stored Gemini operation result.
 * @member {String} operationResultId
 */
CreateOperatorQueueItemRequest.prototype['operationResultId'] = undefined;






export default CreateOperatorQueueItemRequest;

