/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EstimateOperation200Response from './EstimateOperation200Response';
import EstimateOperationRequestTarget from './EstimateOperationRequestTarget';

/**
 * The CreateOperation201Response model module.
 * @module model/CreateOperation201Response
 * @version 0.1.0
 */
class CreateOperation201Response {
    /**
     * Constructs a new <code>CreateOperation201Response</code>.
     * @alias module:model/CreateOperation201Response
     * @param id {String} 
     * @param operationType {module:model/CreateOperation201Response.OperationTypeEnum} 
     * @param status {module:model/CreateOperation201Response.StatusEnum} 
     * @param target {module:model/EstimateOperationRequestTarget} 
     */
    constructor(id, operationType, status, target) { 
        
        CreateOperation201Response.initialize(this, id, operationType, status, target);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, operationType, status, target) { 
        obj['id'] = id;
        obj['operationType'] = operationType;
        obj['status'] = status;
        obj['target'] = target;
    }

    /**
     * Constructs a <code>CreateOperation201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateOperation201Response} obj Optional instance to populate.
     * @return {module:model/CreateOperation201Response} The populated <code>CreateOperation201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateOperation201Response();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('operationType')) {
                obj['operationType'] = ApiClient.convertToType(data['operationType'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = EstimateOperationRequestTarget.constructFromObject(data['target']);
            }
            if (data.hasOwnProperty('savedPromptId')) {
                obj['savedPromptId'] = ApiClient.convertToType(data['savedPromptId'], 'String');
            }
            if (data.hasOwnProperty('temporaryPromptText')) {
                obj['temporaryPromptText'] = ApiClient.convertToType(data['temporaryPromptText'], 'String');
            }
            if (data.hasOwnProperty('estimate')) {
                obj['estimate'] = EstimateOperation200Response.constructFromObject(data['estimate']);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('completedAt')) {
                obj['completedAt'] = ApiClient.convertToType(data['completedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateOperation201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateOperation201Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateOperation201Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['operationType'] && !(typeof data['operationType'] === 'string' || data['operationType'] instanceof String)) {
            throw new Error("Expected the field `operationType` to be a primitive type in the JSON string but got " + data['operationType']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // validate the optional field `target`
        if (data['target']) { // data not null
          EstimateOperationRequestTarget.validateJSON(data['target']);
        }
        // ensure the json data is a string
        if (data['savedPromptId'] && !(typeof data['savedPromptId'] === 'string' || data['savedPromptId'] instanceof String)) {
            throw new Error("Expected the field `savedPromptId` to be a primitive type in the JSON string but got " + data['savedPromptId']);
        }
        // ensure the json data is a string
        if (data['temporaryPromptText'] && !(typeof data['temporaryPromptText'] === 'string' || data['temporaryPromptText'] instanceof String)) {
            throw new Error("Expected the field `temporaryPromptText` to be a primitive type in the JSON string but got " + data['temporaryPromptText']);
        }
        // validate the optional field `estimate`
        if (data['estimate']) { // data not null
          EstimateOperation200Response.validateJSON(data['estimate']);
        }

        return true;
    }


}

CreateOperation201Response.RequiredProperties = ["id", "operationType", "status", "target"];

/**
 * @member {String} id
 */
CreateOperation201Response.prototype['id'] = undefined;

/**
 * @member {module:model/CreateOperation201Response.OperationTypeEnum} operationType
 */
CreateOperation201Response.prototype['operationType'] = undefined;

/**
 * @member {module:model/CreateOperation201Response.StatusEnum} status
 */
CreateOperation201Response.prototype['status'] = undefined;

/**
 * @member {module:model/EstimateOperationRequestTarget} target
 */
CreateOperation201Response.prototype['target'] = undefined;

/**
 * @member {String} savedPromptId
 */
CreateOperation201Response.prototype['savedPromptId'] = undefined;

/**
 * @member {String} temporaryPromptText
 */
CreateOperation201Response.prototype['temporaryPromptText'] = undefined;

/**
 * @member {module:model/EstimateOperation200Response} estimate
 */
CreateOperation201Response.prototype['estimate'] = undefined;

/**
 * @member {Date} createdAt
 */
CreateOperation201Response.prototype['createdAt'] = undefined;

/**
 * @member {Date} completedAt
 */
CreateOperation201Response.prototype['completedAt'] = undefined;





/**
 * Allowed values for the <code>operationType</code> property.
 * @enum {String}
 * @readonly
 */
CreateOperation201Response['OperationTypeEnum'] = {

    /**
     * value: "find"
     * @const
     */
    "find": "find",

    /**
     * value: "sort"
     * @const
     */
    "sort": "sort",

    /**
     * value: "scan"
     * @const
     */
    "scan": "scan",

    /**
     * value: "summarize"
     * @const
     */
    "summarize": "summarize",

    /**
     * value: "monitor"
     * @const
     */
    "monitor": "monitor"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CreateOperation201Response['StatusEnum'] = {

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "running"
     * @const
     */
    "running": "running",

    /**
     * value: "completed"
     * @const
     */
    "completed": "completed",

    /**
     * value: "failed"
     * @const
     */
    "failed": "failed",

    /**
     * value: "cancelled"
     * @const
     */
    "cancelled": "cancelled"
};



export default CreateOperation201Response;

