/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateCameraGroupRequest model module.
 * @module model/CreateCameraGroupRequest
 * @version 0.1.0
 */
class CreateCameraGroupRequest {
    /**
     * Constructs a new <code>CreateCameraGroupRequest</code>.
     * @alias module:model/CreateCameraGroupRequest
     * @param name {String} 
     */
    constructor(name) { 
        
        CreateCameraGroupRequest.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>CreateCameraGroupRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCameraGroupRequest} obj Optional instance to populate.
     * @return {module:model/CreateCameraGroupRequest} The populated <code>CreateCameraGroupRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCameraGroupRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('cameraIds')) {
                obj['cameraIds'] = ApiClient.convertToType(data['cameraIds'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateCameraGroupRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateCameraGroupRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateCameraGroupRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['cameraIds'])) {
            throw new Error("Expected the field `cameraIds` to be an array in the JSON data but got " + data['cameraIds']);
        }

        return true;
    }


}

CreateCameraGroupRequest.RequiredProperties = ["name"];

/**
 * @member {String} name
 */
CreateCameraGroupRequest.prototype['name'] = undefined;

/**
 * @member {String} description
 */
CreateCameraGroupRequest.prototype['description'] = undefined;

/**
 * @member {Array.<String>} cameraIds
 */
CreateCameraGroupRequest.prototype['cameraIds'] = undefined;






export default CreateCameraGroupRequest;

