/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EstimateOperationRequestTarget from './EstimateOperationRequestTarget';

/**
 * The CreateOperationRequest model module.
 * @module model/CreateOperationRequest
 * @version 0.1.0
 */
class CreateOperationRequest {
    /**
     * Constructs a new <code>CreateOperationRequest</code>.
     * @alias module:model/CreateOperationRequest
     * @param operationType {module:model/CreateOperationRequest.OperationTypeEnum} 
     * @param target {module:model/EstimateOperationRequestTarget} 
     */
    constructor(operationType, target) { 
        
        CreateOperationRequest.initialize(this, operationType, target);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, operationType, target) { 
        obj['operationType'] = operationType;
        obj['target'] = target;
    }

    /**
     * Constructs a <code>CreateOperationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateOperationRequest} obj Optional instance to populate.
     * @return {module:model/CreateOperationRequest} The populated <code>CreateOperationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateOperationRequest();

            if (data.hasOwnProperty('operationType')) {
                obj['operationType'] = ApiClient.convertToType(data['operationType'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = EstimateOperationRequestTarget.constructFromObject(data['target']);
            }
            if (data.hasOwnProperty('savedPromptId')) {
                obj['savedPromptId'] = ApiClient.convertToType(data['savedPromptId'], 'String');
            }
            if (data.hasOwnProperty('temporaryPromptText')) {
                obj['temporaryPromptText'] = ApiClient.convertToType(data['temporaryPromptText'], 'String');
            }
            if (data.hasOwnProperty('maxEstimatedCost')) {
                obj['maxEstimatedCost'] = ApiClient.convertToType(data['maxEstimatedCost'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateOperationRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateOperationRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateOperationRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['operationType'] && !(typeof data['operationType'] === 'string' || data['operationType'] instanceof String)) {
            throw new Error("Expected the field `operationType` to be a primitive type in the JSON string but got " + data['operationType']);
        }
        // validate the optional field `target`
        if (data['target']) { // data not null
          EstimateOperationRequestTarget.validateJSON(data['target']);
        }
        // ensure the json data is a string
        if (data['savedPromptId'] && !(typeof data['savedPromptId'] === 'string' || data['savedPromptId'] instanceof String)) {
            throw new Error("Expected the field `savedPromptId` to be a primitive type in the JSON string but got " + data['savedPromptId']);
        }
        // ensure the json data is a string
        if (data['temporaryPromptText'] && !(typeof data['temporaryPromptText'] === 'string' || data['temporaryPromptText'] instanceof String)) {
            throw new Error("Expected the field `temporaryPromptText` to be a primitive type in the JSON string but got " + data['temporaryPromptText']);
        }

        return true;
    }


}

CreateOperationRequest.RequiredProperties = ["operationType", "target"];

/**
 * @member {module:model/CreateOperationRequest.OperationTypeEnum} operationType
 */
CreateOperationRequest.prototype['operationType'] = undefined;

/**
 * @member {module:model/EstimateOperationRequestTarget} target
 */
CreateOperationRequest.prototype['target'] = undefined;

/**
 * @member {String} savedPromptId
 */
CreateOperationRequest.prototype['savedPromptId'] = undefined;

/**
 * @member {String} temporaryPromptText
 */
CreateOperationRequest.prototype['temporaryPromptText'] = undefined;

/**
 * @member {Number} maxEstimatedCost
 */
CreateOperationRequest.prototype['maxEstimatedCost'] = undefined;





/**
 * Allowed values for the <code>operationType</code> property.
 * @enum {String}
 * @readonly
 */
CreateOperationRequest['OperationTypeEnum'] = {

    /**
     * value: "find"
     * @const
     */
    "find": "find",

    /**
     * value: "sort"
     * @const
     */
    "sort": "sort",

    /**
     * value: "scan"
     * @const
     */
    "scan": "scan",

    /**
     * value: "summarize"
     * @const
     */
    "summarize": "summarize",

    /**
     * value: "monitor"
     * @const
     */
    "monitor": "monitor"
};



export default CreateOperationRequest;

