/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateSavedPromptRequest model module.
 * @module model/CreateSavedPromptRequest
 * @version 0.1.0
 */
class CreateSavedPromptRequest {
    /**
     * Constructs a new <code>CreateSavedPromptRequest</code>.
     * @alias module:model/CreateSavedPromptRequest
     * @param name {String} 
     * @param promptType {module:model/CreateSavedPromptRequest.PromptTypeEnum} 
     * @param promptText {String} 
     */
    constructor(name, promptType, promptText) { 
        
        CreateSavedPromptRequest.initialize(this, name, promptType, promptText);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, promptType, promptText) { 
        obj['name'] = name;
        obj['promptType'] = promptType;
        obj['promptText'] = promptText;
        obj['enabled'] = true;
    }

    /**
     * Constructs a <code>CreateSavedPromptRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateSavedPromptRequest} obj Optional instance to populate.
     * @return {module:model/CreateSavedPromptRequest} The populated <code>CreateSavedPromptRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateSavedPromptRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('promptType')) {
                obj['promptType'] = ApiClient.convertToType(data['promptType'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('promptText')) {
                obj['promptText'] = ApiClient.convertToType(data['promptText'], 'String');
            }
            if (data.hasOwnProperty('defaultPriority')) {
                obj['defaultPriority'] = ApiClient.convertToType(data['defaultPriority'], 'String');
            }
            if (data.hasOwnProperty('defaultMaxEstimatedCost')) {
                obj['defaultMaxEstimatedCost'] = ApiClient.convertToType(data['defaultMaxEstimatedCost'], 'Number');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateSavedPromptRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateSavedPromptRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateSavedPromptRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['promptType'] && !(typeof data['promptType'] === 'string' || data['promptType'] instanceof String)) {
            throw new Error("Expected the field `promptType` to be a primitive type in the JSON string but got " + data['promptType']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['promptText'] && !(typeof data['promptText'] === 'string' || data['promptText'] instanceof String)) {
            throw new Error("Expected the field `promptText` to be a primitive type in the JSON string but got " + data['promptText']);
        }
        // ensure the json data is a string
        if (data['defaultPriority'] && !(typeof data['defaultPriority'] === 'string' || data['defaultPriority'] instanceof String)) {
            throw new Error("Expected the field `defaultPriority` to be a primitive type in the JSON string but got " + data['defaultPriority']);
        }

        return true;
    }


}

CreateSavedPromptRequest.RequiredProperties = ["name", "promptType", "promptText"];

/**
 * @member {String} name
 */
CreateSavedPromptRequest.prototype['name'] = undefined;

/**
 * @member {module:model/CreateSavedPromptRequest.PromptTypeEnum} promptType
 */
CreateSavedPromptRequest.prototype['promptType'] = undefined;

/**
 * @member {String} description
 */
CreateSavedPromptRequest.prototype['description'] = undefined;

/**
 * @member {String} promptText
 */
CreateSavedPromptRequest.prototype['promptText'] = undefined;

/**
 * @member {module:model/CreateSavedPromptRequest.DefaultPriorityEnum} defaultPriority
 */
CreateSavedPromptRequest.prototype['defaultPriority'] = undefined;

/**
 * @member {Number} defaultMaxEstimatedCost
 */
CreateSavedPromptRequest.prototype['defaultMaxEstimatedCost'] = undefined;

/**
 * @member {Boolean} enabled
 * @default true
 */
CreateSavedPromptRequest.prototype['enabled'] = true;





/**
 * Allowed values for the <code>promptType</code> property.
 * @enum {String}
 * @readonly
 */
CreateSavedPromptRequest['PromptTypeEnum'] = {

    /**
     * value: "sorting"
     * @const
     */
    "sorting": "sorting",

    /**
     * value: "finding"
     * @const
     */
    "finding": "finding",

    /**
     * value: "monitoring"
     * @const
     */
    "monitoring": "monitoring",

    /**
     * value: "summarization"
     * @const
     */
    "summarization": "summarization"
};


/**
 * Allowed values for the <code>defaultPriority</code> property.
 * @enum {String}
 * @readonly
 */
CreateSavedPromptRequest['DefaultPriorityEnum'] = {

    /**
     * value: "low"
     * @const
     */
    "low": "low",

    /**
     * value: "normal"
     * @const
     */
    "normal": "normal",

    /**
     * value: "high"
     * @const
     */
    "high": "high",

    /**
     * value: "emergency"
     * @const
     */
    "emergency": "emergency"
};



export default CreateSavedPromptRequest;

