/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetProxiedCameraSnapshot200ResponseFrame from './GetProxiedCameraSnapshot200ResponseFrame';

/**
 * The GetProxiedCameraSnapshot200Response model module.
 * @module model/GetProxiedCameraSnapshot200Response
 * @version 0.1.0
 */
class GetProxiedCameraSnapshot200Response {
    /**
     * Constructs a new <code>GetProxiedCameraSnapshot200Response</code>.
     * @alias module:model/GetProxiedCameraSnapshot200Response
     * @param snapshotId {String} Opaque id for this snapshot request. This is not necessarily the source frame id.
     * @param cameraId {String} 
     * @param frame {module:model/GetProxiedCameraSnapshot200ResponseFrame} 
     */
    constructor(snapshotId, cameraId, frame) { 
        
        GetProxiedCameraSnapshot200Response.initialize(this, snapshotId, cameraId, frame);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, snapshotId, cameraId, frame) { 
        obj['snapshotId'] = snapshotId;
        obj['cameraId'] = cameraId;
        obj['frame'] = frame;
    }

    /**
     * Constructs a <code>GetProxiedCameraSnapshot200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetProxiedCameraSnapshot200Response} obj Optional instance to populate.
     * @return {module:model/GetProxiedCameraSnapshot200Response} The populated <code>GetProxiedCameraSnapshot200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetProxiedCameraSnapshot200Response();

            if (data.hasOwnProperty('snapshotId')) {
                obj['snapshotId'] = ApiClient.convertToType(data['snapshotId'], 'String');
            }
            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'String');
            }
            if (data.hasOwnProperty('frame')) {
                obj['frame'] = GetProxiedCameraSnapshot200ResponseFrame.constructFromObject(data['frame']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetProxiedCameraSnapshot200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetProxiedCameraSnapshot200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetProxiedCameraSnapshot200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['snapshotId'] && !(typeof data['snapshotId'] === 'string' || data['snapshotId'] instanceof String)) {
            throw new Error("Expected the field `snapshotId` to be a primitive type in the JSON string but got " + data['snapshotId']);
        }
        // ensure the json data is a string
        if (data['cameraId'] && !(typeof data['cameraId'] === 'string' || data['cameraId'] instanceof String)) {
            throw new Error("Expected the field `cameraId` to be a primitive type in the JSON string but got " + data['cameraId']);
        }
        // validate the optional field `frame`
        if (data['frame']) { // data not null
          GetProxiedCameraSnapshot200ResponseFrame.validateJSON(data['frame']);
        }

        return true;
    }


}

GetProxiedCameraSnapshot200Response.RequiredProperties = ["snapshotId", "cameraId", "frame"];

/**
 * Opaque id for this snapshot request. This is not necessarily the source frame id.
 * @member {String} snapshotId
 */
GetProxiedCameraSnapshot200Response.prototype['snapshotId'] = undefined;

/**
 * @member {String} cameraId
 */
GetProxiedCameraSnapshot200Response.prototype['cameraId'] = undefined;

/**
 * @member {module:model/GetProxiedCameraSnapshot200ResponseFrame} frame
 */
GetProxiedCameraSnapshot200Response.prototype['frame'] = undefined;






export default GetProxiedCameraSnapshot200Response;

