/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListOperationResults200ResponseResultsInner from './ListOperationResults200ResponseResultsInner';

/**
 * The ListOperationResults200Response model module.
 * @module model/ListOperationResults200Response
 * @version 0.1.0
 */
class ListOperationResults200Response {
    /**
     * Constructs a new <code>ListOperationResults200Response</code>.
     * @alias module:model/ListOperationResults200Response
     * @param results {Array.<module:model/ListOperationResults200ResponseResultsInner>} 
     */
    constructor(results) { 
        
        ListOperationResults200Response.initialize(this, results);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, results) { 
        obj['results'] = results;
    }

    /**
     * Constructs a <code>ListOperationResults200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListOperationResults200Response} obj Optional instance to populate.
     * @return {module:model/ListOperationResults200Response} The populated <code>ListOperationResults200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListOperationResults200Response();

            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [ListOperationResults200ResponseResultsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListOperationResults200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListOperationResults200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListOperationResults200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                ListOperationResults200ResponseResultsInner.validateJSON(item);
            };
        }

        return true;
    }


}

ListOperationResults200Response.RequiredProperties = ["results"];

/**
 * @member {Array.<module:model/ListOperationResults200ResponseResultsInner>} results
 */
ListOperationResults200Response.prototype['results'] = undefined;






export default ListOperationResults200Response;

