/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListOperatorQueueItems200ResponseItemsInnerAction from './ListOperatorQueueItems200ResponseItemsInnerAction';
import ListOperatorQueueItems200ResponseItemsInnerScore from './ListOperatorQueueItems200ResponseItemsInnerScore';

/**
 * The ListOperatorQueueItems200ResponseItemsInner model module.
 * @module model/ListOperatorQueueItems200ResponseItemsInner
 * @version 0.1.0
 */
class ListOperatorQueueItems200ResponseItemsInner {
    /**
     * Constructs a new <code>ListOperatorQueueItems200ResponseItemsInner</code>.
     * @alias module:model/ListOperatorQueueItems200ResponseItemsInner
     * @param id {String} 
     * @param cameraId {String} 
     * @param cameraGroupId {String} 
     * @param action {module:model/ListOperatorQueueItems200ResponseItemsInnerAction} 
     * @param score {module:model/ListOperatorQueueItems200ResponseItemsInnerScore} 
     * @param status {module:model/ListOperatorQueueItems200ResponseItemsInner.StatusEnum} 
     */
    constructor(id, cameraId, cameraGroupId, action, score, status) { 
        
        ListOperatorQueueItems200ResponseItemsInner.initialize(this, id, cameraId, cameraGroupId, action, score, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, cameraId, cameraGroupId, action, score, status) { 
        obj['id'] = id;
        obj['cameraId'] = cameraId;
        obj['cameraGroupId'] = cameraGroupId;
        obj['action'] = action;
        obj['score'] = score;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>ListOperatorQueueItems200ResponseItemsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListOperatorQueueItems200ResponseItemsInner} obj Optional instance to populate.
     * @return {module:model/ListOperatorQueueItems200ResponseItemsInner} The populated <code>ListOperatorQueueItems200ResponseItemsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListOperatorQueueItems200ResponseItemsInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('operationId')) {
                obj['operationId'] = ApiClient.convertToType(data['operationId'], 'String');
            }
            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'String');
            }
            if (data.hasOwnProperty('cameraGroupId')) {
                obj['cameraGroupId'] = ApiClient.convertToType(data['cameraGroupId'], 'String');
            }
            if (data.hasOwnProperty('savedPromptId')) {
                obj['savedPromptId'] = ApiClient.convertToType(data['savedPromptId'], 'String');
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = ListOperatorQueueItems200ResponseItemsInnerAction.constructFromObject(data['action']);
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ListOperatorQueueItems200ResponseItemsInnerScore.constructFromObject(data['score']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListOperatorQueueItems200ResponseItemsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListOperatorQueueItems200ResponseItemsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListOperatorQueueItems200ResponseItemsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['operationId'] && !(typeof data['operationId'] === 'string' || data['operationId'] instanceof String)) {
            throw new Error("Expected the field `operationId` to be a primitive type in the JSON string but got " + data['operationId']);
        }
        // ensure the json data is a string
        if (data['cameraId'] && !(typeof data['cameraId'] === 'string' || data['cameraId'] instanceof String)) {
            throw new Error("Expected the field `cameraId` to be a primitive type in the JSON string but got " + data['cameraId']);
        }
        // ensure the json data is a string
        if (data['cameraGroupId'] && !(typeof data['cameraGroupId'] === 'string' || data['cameraGroupId'] instanceof String)) {
            throw new Error("Expected the field `cameraGroupId` to be a primitive type in the JSON string but got " + data['cameraGroupId']);
        }
        // ensure the json data is a string
        if (data['savedPromptId'] && !(typeof data['savedPromptId'] === 'string' || data['savedPromptId'] instanceof String)) {
            throw new Error("Expected the field `savedPromptId` to be a primitive type in the JSON string but got " + data['savedPromptId']);
        }
        // validate the optional field `action`
        if (data['action']) { // data not null
          ListOperatorQueueItems200ResponseItemsInnerAction.validateJSON(data['action']);
        }
        // validate the optional field `score`
        if (data['score']) { // data not null
          ListOperatorQueueItems200ResponseItemsInnerScore.validateJSON(data['score']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

ListOperatorQueueItems200ResponseItemsInner.RequiredProperties = ["id", "cameraId", "cameraGroupId", "action", "score", "status"];

/**
 * @member {String} id
 */
ListOperatorQueueItems200ResponseItemsInner.prototype['id'] = undefined;

/**
 * @member {String} operationId
 */
ListOperatorQueueItems200ResponseItemsInner.prototype['operationId'] = undefined;

/**
 * @member {String} cameraId
 */
ListOperatorQueueItems200ResponseItemsInner.prototype['cameraId'] = undefined;

/**
 * @member {String} cameraGroupId
 */
ListOperatorQueueItems200ResponseItemsInner.prototype['cameraGroupId'] = undefined;

/**
 * @member {String} savedPromptId
 */
ListOperatorQueueItems200ResponseItemsInner.prototype['savedPromptId'] = undefined;

/**
 * @member {module:model/ListOperatorQueueItems200ResponseItemsInnerAction} action
 */
ListOperatorQueueItems200ResponseItemsInner.prototype['action'] = undefined;

/**
 * @member {module:model/ListOperatorQueueItems200ResponseItemsInnerScore} score
 */
ListOperatorQueueItems200ResponseItemsInner.prototype['score'] = undefined;

/**
 * @member {module:model/ListOperatorQueueItems200ResponseItemsInner.StatusEnum} status
 */
ListOperatorQueueItems200ResponseItemsInner.prototype['status'] = undefined;

/**
 * @member {Date} createdAt
 */
ListOperatorQueueItems200ResponseItemsInner.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
ListOperatorQueueItems200ResponseItemsInner.prototype['updatedAt'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ListOperatorQueueItems200ResponseItemsInner['StatusEnum'] = {

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "acknowledged"
     * @const
     */
    "acknowledged": "acknowledged",

    /**
     * value: "dismissed"
     * @const
     */
    "dismissed": "dismissed",

    /**
     * value: "completed"
     * @const
     */
    "completed": "completed"
};



export default ListOperatorQueueItems200ResponseItemsInner;

