/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListOperationSecondPassResults200ResponseResultsInner model module.
 * @module model/ListOperationSecondPassResults200ResponseResultsInner
 * @version 0.1.0
 */
class ListOperationSecondPassResults200ResponseResultsInner {
    /**
     * Constructs a new <code>ListOperationSecondPassResults200ResponseResultsInner</code>.
     * @alias module:model/ListOperationSecondPassResults200ResponseResultsInner
     * @param id {String} 
     * @param operationId {String} 
     * @param cameraId {String} 
     * @param firstPassResultId {String} 
     * @param frameRefId {String} 
     * @param frameUrl {String} 
     * @param include {Boolean} True when this result should appear in the final prompt result camera list.
     * @param promptScore {Number} Final global score used for sorting/finding results for this prompt operation.
     * @param operatorPriorityScore {Number} Final urgency score used by the operator action queue.
     * @param operatorAction {String} 
     * @param reason {String} 
     */
    constructor(id, operationId, cameraId, firstPassResultId, frameRefId, frameUrl, include, promptScore, operatorPriorityScore, operatorAction, reason) { 
        
        ListOperationSecondPassResults200ResponseResultsInner.initialize(this, id, operationId, cameraId, firstPassResultId, frameRefId, frameUrl, include, promptScore, operatorPriorityScore, operatorAction, reason);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, operationId, cameraId, firstPassResultId, frameRefId, frameUrl, include, promptScore, operatorPriorityScore, operatorAction, reason) { 
        obj['id'] = id;
        obj['operationId'] = operationId;
        obj['cameraId'] = cameraId;
        obj['firstPassResultId'] = firstPassResultId;
        obj['frameRefId'] = frameRefId;
        obj['frameUrl'] = frameUrl;
        obj['include'] = include;
        obj['promptScore'] = promptScore;
        obj['operatorPriorityScore'] = operatorPriorityScore;
        obj['operatorAction'] = operatorAction;
        obj['reason'] = reason;
    }

    /**
     * Constructs a <code>ListOperationSecondPassResults200ResponseResultsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListOperationSecondPassResults200ResponseResultsInner} obj Optional instance to populate.
     * @return {module:model/ListOperationSecondPassResults200ResponseResultsInner} The populated <code>ListOperationSecondPassResults200ResponseResultsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListOperationSecondPassResults200ResponseResultsInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('operationId')) {
                obj['operationId'] = ApiClient.convertToType(data['operationId'], 'String');
            }
            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'String');
            }
            if (data.hasOwnProperty('cameraGroupId')) {
                obj['cameraGroupId'] = ApiClient.convertToType(data['cameraGroupId'], 'String');
            }
            if (data.hasOwnProperty('promptId')) {
                obj['promptId'] = ApiClient.convertToType(data['promptId'], 'String');
            }
            if (data.hasOwnProperty('firstPassResultId')) {
                obj['firstPassResultId'] = ApiClient.convertToType(data['firstPassResultId'], 'String');
            }
            if (data.hasOwnProperty('frameRefId')) {
                obj['frameRefId'] = ApiClient.convertToType(data['frameRefId'], 'String');
            }
            if (data.hasOwnProperty('frameUrl')) {
                obj['frameUrl'] = ApiClient.convertToType(data['frameUrl'], 'String');
            }
            if (data.hasOwnProperty('include')) {
                obj['include'] = ApiClient.convertToType(data['include'], 'Boolean');
            }
            if (data.hasOwnProperty('globalRank')) {
                obj['globalRank'] = ApiClient.convertToType(data['globalRank'], 'Number');
            }
            if (data.hasOwnProperty('promptScore')) {
                obj['promptScore'] = ApiClient.convertToType(data['promptScore'], 'Number');
            }
            if (data.hasOwnProperty('operatorPriorityScore')) {
                obj['operatorPriorityScore'] = ApiClient.convertToType(data['operatorPriorityScore'], 'Number');
            }
            if (data.hasOwnProperty('operatorAction')) {
                obj['operatorAction'] = ApiClient.convertToType(data['operatorAction'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('rawModelJson')) {
                obj['rawModelJson'] = ApiClient.convertToType(data['rawModelJson'], {'String': Object});
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListOperationSecondPassResults200ResponseResultsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListOperationSecondPassResults200ResponseResultsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListOperationSecondPassResults200ResponseResultsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['operationId'] && !(typeof data['operationId'] === 'string' || data['operationId'] instanceof String)) {
            throw new Error("Expected the field `operationId` to be a primitive type in the JSON string but got " + data['operationId']);
        }
        // ensure the json data is a string
        if (data['cameraId'] && !(typeof data['cameraId'] === 'string' || data['cameraId'] instanceof String)) {
            throw new Error("Expected the field `cameraId` to be a primitive type in the JSON string but got " + data['cameraId']);
        }
        // ensure the json data is a string
        if (data['cameraGroupId'] && !(typeof data['cameraGroupId'] === 'string' || data['cameraGroupId'] instanceof String)) {
            throw new Error("Expected the field `cameraGroupId` to be a primitive type in the JSON string but got " + data['cameraGroupId']);
        }
        // ensure the json data is a string
        if (data['promptId'] && !(typeof data['promptId'] === 'string' || data['promptId'] instanceof String)) {
            throw new Error("Expected the field `promptId` to be a primitive type in the JSON string but got " + data['promptId']);
        }
        // ensure the json data is a string
        if (data['firstPassResultId'] && !(typeof data['firstPassResultId'] === 'string' || data['firstPassResultId'] instanceof String)) {
            throw new Error("Expected the field `firstPassResultId` to be a primitive type in the JSON string but got " + data['firstPassResultId']);
        }
        // ensure the json data is a string
        if (data['frameRefId'] && !(typeof data['frameRefId'] === 'string' || data['frameRefId'] instanceof String)) {
            throw new Error("Expected the field `frameRefId` to be a primitive type in the JSON string but got " + data['frameRefId']);
        }
        // ensure the json data is a string
        if (data['frameUrl'] && !(typeof data['frameUrl'] === 'string' || data['frameUrl'] instanceof String)) {
            throw new Error("Expected the field `frameUrl` to be a primitive type in the JSON string but got " + data['frameUrl']);
        }
        // ensure the json data is a string
        if (data['operatorAction'] && !(typeof data['operatorAction'] === 'string' || data['operatorAction'] instanceof String)) {
            throw new Error("Expected the field `operatorAction` to be a primitive type in the JSON string but got " + data['operatorAction']);
        }
        // ensure the json data is a string
        if (data['reason'] && !(typeof data['reason'] === 'string' || data['reason'] instanceof String)) {
            throw new Error("Expected the field `reason` to be a primitive type in the JSON string but got " + data['reason']);
        }

        return true;
    }


}

ListOperationSecondPassResults200ResponseResultsInner.RequiredProperties = ["id", "operationId", "cameraId", "firstPassResultId", "frameRefId", "frameUrl", "include", "promptScore", "operatorPriorityScore", "operatorAction", "reason"];

/**
 * @member {String} id
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['id'] = undefined;

/**
 * @member {String} operationId
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['operationId'] = undefined;

/**
 * @member {String} cameraId
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['cameraId'] = undefined;

/**
 * @member {String} cameraGroupId
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['cameraGroupId'] = undefined;

/**
 * @member {String} promptId
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['promptId'] = undefined;

/**
 * @member {String} firstPassResultId
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['firstPassResultId'] = undefined;

/**
 * @member {String} frameRefId
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['frameRefId'] = undefined;

/**
 * @member {String} frameUrl
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['frameUrl'] = undefined;

/**
 * True when this result should appear in the final prompt result camera list.
 * @member {Boolean} include
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['include'] = undefined;

/**
 * Rank assigned by the second pass. Lower values are higher priority.
 * @member {Number} globalRank
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['globalRank'] = undefined;

/**
 * Final global score used for sorting/finding results for this prompt operation.
 * @member {Number} promptScore
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['promptScore'] = undefined;

/**
 * Final urgency score used by the operator action queue.
 * @member {Number} operatorPriorityScore
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['operatorPriorityScore'] = undefined;

/**
 * @member {String} operatorAction
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['operatorAction'] = undefined;

/**
 * @member {String} reason
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['reason'] = undefined;

/**
 * @member {Object.<String, Object>} rawModelJson
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['rawModelJson'] = undefined;

/**
 * @member {Date} createdAt
 */
ListOperationSecondPassResults200ResponseResultsInner.prototype['createdAt'] = undefined;






export default ListOperationSecondPassResults200ResponseResultsInner;

