/**
 * CamBot REST API
 * Product API used by the CamBot client.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListOperationResults200ResponseResultsInner model module.
 * @module model/ListOperationResults200ResponseResultsInner
 * @version 0.1.0
 */
class ListOperationResults200ResponseResultsInner {
    /**
     * Constructs a new <code>ListOperationResults200ResponseResultsInner</code>.
     * @alias module:model/ListOperationResults200ResponseResultsInner
     * @param id {String} 
     * @param operationId {String} 
     * @param cameraId {String} 
     * @param frameRefId {String} 
     * @param frameUrl {String} 
     * @param include {Boolean} True when the result should appear in the prompt result camera list.
     * @param promptMatchScore {Number} Score from 0 to 100 indicating how strongly the snapshot matches the prompt.
     * @param operatorPriorityScore {Number} Score from 0 to 100 indicating how urgently an operator should handle this recommended action.
     * @param recommendedAction {String} 
     * @param reason {String} 
     */
    constructor(id, operationId, cameraId, frameRefId, frameUrl, include, promptMatchScore, operatorPriorityScore, recommendedAction, reason) { 
        
        ListOperationResults200ResponseResultsInner.initialize(this, id, operationId, cameraId, frameRefId, frameUrl, include, promptMatchScore, operatorPriorityScore, recommendedAction, reason);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, operationId, cameraId, frameRefId, frameUrl, include, promptMatchScore, operatorPriorityScore, recommendedAction, reason) { 
        obj['id'] = id;
        obj['operationId'] = operationId;
        obj['cameraId'] = cameraId;
        obj['frameRefId'] = frameRefId;
        obj['frameUrl'] = frameUrl;
        obj['include'] = include;
        obj['promptMatchScore'] = promptMatchScore;
        obj['operatorPriorityScore'] = operatorPriorityScore;
        obj['recommendedAction'] = recommendedAction;
        obj['reason'] = reason;
    }

    /**
     * Constructs a <code>ListOperationResults200ResponseResultsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListOperationResults200ResponseResultsInner} obj Optional instance to populate.
     * @return {module:model/ListOperationResults200ResponseResultsInner} The populated <code>ListOperationResults200ResponseResultsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListOperationResults200ResponseResultsInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('operationId')) {
                obj['operationId'] = ApiClient.convertToType(data['operationId'], 'String');
            }
            if (data.hasOwnProperty('cameraId')) {
                obj['cameraId'] = ApiClient.convertToType(data['cameraId'], 'String');
            }
            if (data.hasOwnProperty('cameraGroupId')) {
                obj['cameraGroupId'] = ApiClient.convertToType(data['cameraGroupId'], 'String');
            }
            if (data.hasOwnProperty('promptId')) {
                obj['promptId'] = ApiClient.convertToType(data['promptId'], 'String');
            }
            if (data.hasOwnProperty('frameRefId')) {
                obj['frameRefId'] = ApiClient.convertToType(data['frameRefId'], 'String');
            }
            if (data.hasOwnProperty('frameUrl')) {
                obj['frameUrl'] = ApiClient.convertToType(data['frameUrl'], 'String');
            }
            if (data.hasOwnProperty('include')) {
                obj['include'] = ApiClient.convertToType(data['include'], 'Boolean');
            }
            if (data.hasOwnProperty('promptMatchScore')) {
                obj['promptMatchScore'] = ApiClient.convertToType(data['promptMatchScore'], 'Number');
            }
            if (data.hasOwnProperty('operatorPriorityScore')) {
                obj['operatorPriorityScore'] = ApiClient.convertToType(data['operatorPriorityScore'], 'Number');
            }
            if (data.hasOwnProperty('recommendedAction')) {
                obj['recommendedAction'] = ApiClient.convertToType(data['recommendedAction'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('rawModelJson')) {
                obj['rawModelJson'] = ApiClient.convertToType(data['rawModelJson'], {'String': Object});
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListOperationResults200ResponseResultsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListOperationResults200ResponseResultsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListOperationResults200ResponseResultsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['operationId'] && !(typeof data['operationId'] === 'string' || data['operationId'] instanceof String)) {
            throw new Error("Expected the field `operationId` to be a primitive type in the JSON string but got " + data['operationId']);
        }
        // ensure the json data is a string
        if (data['cameraId'] && !(typeof data['cameraId'] === 'string' || data['cameraId'] instanceof String)) {
            throw new Error("Expected the field `cameraId` to be a primitive type in the JSON string but got " + data['cameraId']);
        }
        // ensure the json data is a string
        if (data['cameraGroupId'] && !(typeof data['cameraGroupId'] === 'string' || data['cameraGroupId'] instanceof String)) {
            throw new Error("Expected the field `cameraGroupId` to be a primitive type in the JSON string but got " + data['cameraGroupId']);
        }
        // ensure the json data is a string
        if (data['promptId'] && !(typeof data['promptId'] === 'string' || data['promptId'] instanceof String)) {
            throw new Error("Expected the field `promptId` to be a primitive type in the JSON string but got " + data['promptId']);
        }
        // ensure the json data is a string
        if (data['frameRefId'] && !(typeof data['frameRefId'] === 'string' || data['frameRefId'] instanceof String)) {
            throw new Error("Expected the field `frameRefId` to be a primitive type in the JSON string but got " + data['frameRefId']);
        }
        // ensure the json data is a string
        if (data['frameUrl'] && !(typeof data['frameUrl'] === 'string' || data['frameUrl'] instanceof String)) {
            throw new Error("Expected the field `frameUrl` to be a primitive type in the JSON string but got " + data['frameUrl']);
        }
        // ensure the json data is a string
        if (data['recommendedAction'] && !(typeof data['recommendedAction'] === 'string' || data['recommendedAction'] instanceof String)) {
            throw new Error("Expected the field `recommendedAction` to be a primitive type in the JSON string but got " + data['recommendedAction']);
        }
        // ensure the json data is a string
        if (data['reason'] && !(typeof data['reason'] === 'string' || data['reason'] instanceof String)) {
            throw new Error("Expected the field `reason` to be a primitive type in the JSON string but got " + data['reason']);
        }

        return true;
    }


}

ListOperationResults200ResponseResultsInner.RequiredProperties = ["id", "operationId", "cameraId", "frameRefId", "frameUrl", "include", "promptMatchScore", "operatorPriorityScore", "recommendedAction", "reason"];

/**
 * @member {String} id
 */
ListOperationResults200ResponseResultsInner.prototype['id'] = undefined;

/**
 * @member {String} operationId
 */
ListOperationResults200ResponseResultsInner.prototype['operationId'] = undefined;

/**
 * @member {String} cameraId
 */
ListOperationResults200ResponseResultsInner.prototype['cameraId'] = undefined;

/**
 * @member {String} cameraGroupId
 */
ListOperationResults200ResponseResultsInner.prototype['cameraGroupId'] = undefined;

/**
 * @member {String} promptId
 */
ListOperationResults200ResponseResultsInner.prototype['promptId'] = undefined;

/**
 * @member {String} frameRefId
 */
ListOperationResults200ResponseResultsInner.prototype['frameRefId'] = undefined;

/**
 * @member {String} frameUrl
 */
ListOperationResults200ResponseResultsInner.prototype['frameUrl'] = undefined;

/**
 * True when the result should appear in the prompt result camera list.
 * @member {Boolean} include
 */
ListOperationResults200ResponseResultsInner.prototype['include'] = undefined;

/**
 * Score from 0 to 100 indicating how strongly the snapshot matches the prompt.
 * @member {Number} promptMatchScore
 */
ListOperationResults200ResponseResultsInner.prototype['promptMatchScore'] = undefined;

/**
 * Score from 0 to 100 indicating how urgently an operator should handle this recommended action.
 * @member {Number} operatorPriorityScore
 */
ListOperationResults200ResponseResultsInner.prototype['operatorPriorityScore'] = undefined;

/**
 * @member {String} recommendedAction
 */
ListOperationResults200ResponseResultsInner.prototype['recommendedAction'] = undefined;

/**
 * @member {String} reason
 */
ListOperationResults200ResponseResultsInner.prototype['reason'] = undefined;

/**
 * @member {Object.<String, Object>} rawModelJson
 */
ListOperationResults200ResponseResultsInner.prototype['rawModelJson'] = undefined;

/**
 * @member {Date} createdAt
 */
ListOperationResults200ResponseResultsInner.prototype['createdAt'] = undefined;






export default ListOperationResults200ResponseResultsInner;

