# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: operator_queue.sql
import dataclasses
from typing import Any, AsyncIterator, Iterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from db import models


CREATE_OPERATOR_QUEUE_ITEM = """-- name: create_operator_queue_item \\:one
INSERT INTO operator_queue_items (
  id, operation_id, camera_id, camera_group_id, saved_prompt_id,
  title, description, recommended_action,
  confidence, urgency, risk, overall, status
)
VALUES (
  COALESCE(NULLIF(:p1, ''), gen_random_uuid()\\:\\:text), :p2, :p3, :p4, :p5,
  :p6, :p7, :p8, COALESCE(:p9, 0), COALESCE(:p10, 0), COALESCE(:p11, 0), COALESCE(:p12, 0), COALESCE(:p13, 'pending')
)
RETURNING id, operation_id, camera_id, camera_group_id, saved_prompt_id, title, description, recommended_action, confidence, urgency, risk, overall, status, operator_note, created_at, updated_at
"""


@dataclasses.dataclass()
class CreateOperatorQueueItemParams:
    column_1: Optional[Any]
    operation_id: Optional[str]
    camera_id: str
    camera_group_id: Optional[str]
    saved_prompt_id: Optional[str]
    title: str
    description: str
    recommended_action: Optional[str]
    column_9: Optional[Any]
    column_10: Optional[Any]
    column_11: Optional[Any]
    column_12: Optional[Any]
    column_13: Optional[Any]


LIST_OPERATOR_QUEUE_ITEMS = """-- name: list_operator_queue_items \\:many
SELECT id, operation_id, camera_id, camera_group_id, saved_prompt_id, title, description, recommended_action, confidence, urgency, risk, overall, status, operator_note, created_at, updated_at
FROM operator_queue_items
ORDER BY
  CASE status
    WHEN 'pending' THEN 0
    WHEN 'acknowledged' THEN 1
    WHEN 'completed' THEN 2
    WHEN 'dismissed' THEN 3
    ELSE 4
  END,
  overall DESC,
  created_at DESC
LIMIT :p1 OFFSET :p2
"""


UPDATE_OPERATOR_QUEUE_ITEM_STATUS = """-- name: update_operator_queue_item_status \\:one
UPDATE operator_queue_items
SET status = :p2, operator_note = COALESCE(:p3, operator_note)
WHERE id = :p1
RETURNING id, operation_id, camera_id, camera_group_id, saved_prompt_id, title, description, recommended_action, confidence, urgency, risk, overall, status, operator_note, created_at, updated_at
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_operator_queue_item(self, arg: CreateOperatorQueueItemParams) -> Optional[models.OperatorQueueItem]:
        row = self._conn.execute(sqlalchemy.text(CREATE_OPERATOR_QUEUE_ITEM), {
            "p1": arg.column_1,
            "p2": arg.operation_id,
            "p3": arg.camera_id,
            "p4": arg.camera_group_id,
            "p5": arg.saved_prompt_id,
            "p6": arg.title,
            "p7": arg.description,
            "p8": arg.recommended_action,
            "p9": arg.column_9,
            "p10": arg.column_10,
            "p11": arg.column_11,
            "p12": arg.column_12,
            "p13": arg.column_13,
        }).first()
        if row is None:
            return None
        return models.OperatorQueueItem(
            id=row[0],
            operation_id=row[1],
            camera_id=row[2],
            camera_group_id=row[3],
            saved_prompt_id=row[4],
            title=row[5],
            description=row[6],
            recommended_action=row[7],
            confidence=row[8],
            urgency=row[9],
            risk=row[10],
            overall=row[11],
            status=row[12],
            operator_note=row[13],
            created_at=row[14],
            updated_at=row[15],
        )

    def list_operator_queue_items(self, *, limit: int, offset: int) -> Iterator[models.OperatorQueueItem]:
        result = self._conn.execute(sqlalchemy.text(LIST_OPERATOR_QUEUE_ITEMS), {"p1": limit, "p2": offset})
        for row in result:
            yield models.OperatorQueueItem(
                id=row[0],
                operation_id=row[1],
                camera_id=row[2],
                camera_group_id=row[3],
                saved_prompt_id=row[4],
                title=row[5],
                description=row[6],
                recommended_action=row[7],
                confidence=row[8],
                urgency=row[9],
                risk=row[10],
                overall=row[11],
                status=row[12],
                operator_note=row[13],
                created_at=row[14],
                updated_at=row[15],
            )

    def update_operator_queue_item_status(self, *, id: str, status: str, operator_note: Optional[str]) -> Optional[models.OperatorQueueItem]:
        row = self._conn.execute(sqlalchemy.text(UPDATE_OPERATOR_QUEUE_ITEM_STATUS), {"p1": id, "p2": status, "p3": operator_note}).first()
        if row is None:
            return None
        return models.OperatorQueueItem(
            id=row[0],
            operation_id=row[1],
            camera_id=row[2],
            camera_group_id=row[3],
            saved_prompt_id=row[4],
            title=row[5],
            description=row[6],
            recommended_action=row[7],
            confidence=row[8],
            urgency=row[9],
            risk=row[10],
            overall=row[11],
            status=row[12],
            operator_note=row[13],
            created_at=row[14],
            updated_at=row[15],
        )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_operator_queue_item(self, arg: CreateOperatorQueueItemParams) -> Optional[models.OperatorQueueItem]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_OPERATOR_QUEUE_ITEM), {
            "p1": arg.column_1,
            "p2": arg.operation_id,
            "p3": arg.camera_id,
            "p4": arg.camera_group_id,
            "p5": arg.saved_prompt_id,
            "p6": arg.title,
            "p7": arg.description,
            "p8": arg.recommended_action,
            "p9": arg.column_9,
            "p10": arg.column_10,
            "p11": arg.column_11,
            "p12": arg.column_12,
            "p13": arg.column_13,
        })).first()
        if row is None:
            return None
        return models.OperatorQueueItem(
            id=row[0],
            operation_id=row[1],
            camera_id=row[2],
            camera_group_id=row[3],
            saved_prompt_id=row[4],
            title=row[5],
            description=row[6],
            recommended_action=row[7],
            confidence=row[8],
            urgency=row[9],
            risk=row[10],
            overall=row[11],
            status=row[12],
            operator_note=row[13],
            created_at=row[14],
            updated_at=row[15],
        )

    async def list_operator_queue_items(self, *, limit: int, offset: int) -> AsyncIterator[models.OperatorQueueItem]:
        result = await self._conn.stream(sqlalchemy.text(LIST_OPERATOR_QUEUE_ITEMS), {"p1": limit, "p2": offset})
        async for row in result:
            yield models.OperatorQueueItem(
                id=row[0],
                operation_id=row[1],
                camera_id=row[2],
                camera_group_id=row[3],
                saved_prompt_id=row[4],
                title=row[5],
                description=row[6],
                recommended_action=row[7],
                confidence=row[8],
                urgency=row[9],
                risk=row[10],
                overall=row[11],
                status=row[12],
                operator_note=row[13],
                created_at=row[14],
                updated_at=row[15],
            )

    async def update_operator_queue_item_status(self, *, id: str, status: str, operator_note: Optional[str]) -> Optional[models.OperatorQueueItem]:
        row = (await self._conn.execute(sqlalchemy.text(UPDATE_OPERATOR_QUEUE_ITEM_STATUS), {"p1": id, "p2": status, "p3": operator_note})).first()
        if row is None:
            return None
        return models.OperatorQueueItem(
            id=row[0],
            operation_id=row[1],
            camera_id=row[2],
            camera_group_id=row[3],
            saved_prompt_id=row[4],
            title=row[5],
            description=row[6],
            recommended_action=row[7],
            confidence=row[8],
            urgency=row[9],
            risk=row[10],
            overall=row[11],
            status=row[12],
            operator_note=row[13],
            created_at=row[14],
            updated_at=row[15],
        )
