# coding: utf-8

"""
    CamBot REST API

    Product API used by the CamBot client.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from cambot_dtos.models.list_proxied_integrator_cameras200_response_cameras_inner import ListProxiedIntegratorCameras200ResponseCamerasInner
from typing import Optional, Set
from typing_extensions import Self

class ListProxiedIntegratorCameras200Response(BaseModel):
    """
    ListProxiedIntegratorCameras200Response
    """ # noqa: E501
    cameras: List[ListProxiedIntegratorCameras200ResponseCamerasInner]
    __properties: ClassVar[List[str]] = ["cameras"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListProxiedIntegratorCameras200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in cameras (list)
        _items = []
        if self.cameras:
            for _item_cameras in self.cameras:
                if _item_cameras:
                    _items.append(_item_cameras.to_dict())
            _dict['cameras'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListProxiedIntegratorCameras200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cameras": [ListProxiedIntegratorCameras200ResponseCamerasInner.from_dict(_item) for _item in obj["cameras"]] if obj.get("cameras") is not None else None
        })
        return _obj


