# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
import datetime
import decimal
from typing import Any, List, Optional


@dataclasses.dataclass()
class CameraFrameRef:
    id: str
    camera_id: str
    frame_id: str
    snapshot_id: Optional[str]
    frame_url: str
    sequence_number: Optional[int]
    captured_at: datetime.datetime
    mime_type: str
    width: Optional[int]
    height: Optional[int]
    expires_at: Optional[datetime.datetime]
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class CameraGroup:
    id: str
    name: str
    description: Optional[str]
    camera_ids: List[str]
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class GeminiCallerSetting:
    id: bool
    enabled: bool
    model_name: str
    continuous_scan_enabled: bool
    continuous_scan_interval_seconds: int
    last_continuous_scan_at: Optional[datetime.datetime]
    next_continuous_scan_at: Optional[datetime.datetime]
    gemini_call_delay_ms: int
    max_concurrent_gemini_calls: int
    max_tokens_per_request: int
    max_cost_per_day: decimal.Decimal
    max_cost_per_month: decimal.Decimal
    allow_emergency_override: bool
    updated_at: datetime.datetime


@dataclasses.dataclass()
class Operation:
    id: str
    prompt_id: str
    camera_group_id: str
    prompt_binding_id: Optional[str]
    trigger: str
    status: str
    total_cameras: int
    processed_cameras: int
    matched_cameras: int
    estimated_gemini_calls: Optional[int]
    estimated_token_count: Optional[int]
    estimated_cost: Optional[decimal.Decimal]
    actual_gemini_calls: Optional[int]
    actual_cost: Optional[decimal.Decimal]
    error_message: Optional[str]
    created_at: datetime.datetime
    started_at: Optional[datetime.datetime]
    completed_at: Optional[datetime.datetime]


@dataclasses.dataclass()
class OperationFrameRef:
    operation_id: str
    frame_ref_id: str
    purpose: str
    created_at: datetime.datetime


@dataclasses.dataclass()
class OperationResult:
    id: str
    operation_id: str
    camera_id: str
    camera_group_id: Optional[str]
    prompt_id: Optional[str]
    frame_ref_id: str
    frame_url: str
    include: bool
    prompt_match_score: decimal.Decimal
    operator_priority_score: decimal.Decimal
    recommended_action: str
    reason: str
    raw_model_json: Optional[Any]
    created_at: datetime.datetime


@dataclasses.dataclass()
class OperatorQueueItem:
    id: str
    operation_result_id: str
    operation_id: str
    camera_id: str
    camera_group_id: Optional[str]
    prompt_id: Optional[str]
    frame_ref_id: str
    frame_url: str
    recommended_action: str
    reason: str
    prompt_match_score: decimal.Decimal
    operator_priority_score: decimal.Decimal
    status: str
    operator_note: Optional[str]
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class PromptBinding:
    id: str
    camera_group_id: str
    prompt_id: str
    enabled: bool
    last_run_at: Optional[datetime.datetime]
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class SavedPrompt:
    id: str
    name: str
    description: Optional[str]
    prompt_text: str
    enabled: bool
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class UsageEvent:
    id: str
    operation_id: Optional[str]
    camera_id: Optional[str]
    camera_group_id: Optional[str]
    event_type: str
    estimated_cost: decimal.Decimal
    token_count: int
    created_at: datetime.datetime


@dataclasses.dataclass()
class UsageLimitSetting:
    id: bool
    max_scans_per_day: int
    max_scans_per_month: int
    max_estimated_cost_per_day: decimal.Decimal
    max_estimated_cost_per_month: decimal.Decimal
    block_operations_when_limit_reached: bool
    updated_at: datetime.datetime
