# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: operator_queue.sql
from typing import Any, AsyncIterator, Iterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from db import models


CREATE_OPERATOR_QUEUE_ITEM_FROM_SECOND_PASS_RESULT = """-- name: create_operator_queue_item_from_second_pass_result \\:one
INSERT INTO operator_queue_items (
  id,
  second_pass_result_id,
  operation_id,
  camera_id,
  camera_group_id,
  prompt_id,
  frame_ref_id,
  frame_url,
  prompt_score,
  operator_priority_score,
  operator_action,
  reason,
  status
)
SELECT
  COALESCE(NULLIF(:p1, ''), gen_random_uuid()\\:\\:text) AS id,
  r.id AS second_pass_result_id,
  r.operation_id AS operation_id,
  r.camera_id AS camera_id,
  r.camera_group_id AS camera_group_id,
  r.prompt_id AS prompt_id,
  r.frame_ref_id AS frame_ref_id,
  r.frame_url AS frame_url,
  r.prompt_score AS prompt_score,
  r.operator_priority_score AS operator_priority_score,
  r.operator_action AS operator_action,
  r.reason AS reason,
  COALESCE(:p2, 'queued') AS status
FROM operation_second_pass_results r
WHERE r.id = :p3
ON CONFLICT (second_pass_result_id)
DO UPDATE SET
  prompt_score = EXCLUDED.prompt_score,
  operator_priority_score = EXCLUDED.operator_priority_score,
  operator_action = EXCLUDED.operator_action,
  reason = EXCLUDED.reason,
  updated_at = now()
RETURNING
  id,
  second_pass_result_id,
  operation_id,
  camera_id,
  camera_group_id,
  prompt_id,
  frame_ref_id,
  frame_url,
  prompt_score,
  operator_priority_score,
  operator_action,
  reason,
  status,
  operator_note,
  created_at,
  updated_at
"""


LIST_OPERATOR_QUEUE_ITEMS = """-- name: list_operator_queue_items \\:many
SELECT
  id,
  second_pass_result_id,
  operation_id,
  camera_id,
  camera_group_id,
  prompt_id,
  frame_ref_id,
  frame_url,
  prompt_score,
  operator_priority_score,
  operator_action,
  reason,
  status,
  operator_note,
  created_at,
  updated_at
FROM operator_queue_items
WHERE (:p1\\:\\:text IS NULL OR status = :p1)
ORDER BY
  CASE status
    WHEN 'queued' THEN 0
    WHEN 'acknowledged' THEN 1
    WHEN 'completed' THEN 2
    WHEN 'dismissed' THEN 3
    ELSE 4
  END,
  operator_priority_score DESC,
  prompt_score DESC,
  created_at ASC
LIMIT :p3 OFFSET :p2
"""


UPDATE_OPERATOR_QUEUE_ITEM_STATUS = """-- name: update_operator_queue_item_status \\:one
UPDATE operator_queue_items
SET
  status = :p1,
  operator_note = COALESCE(:p2, operator_note),
  updated_at = now()
WHERE id = :p3
RETURNING
  id,
  second_pass_result_id,
  operation_id,
  camera_id,
  camera_group_id,
  prompt_id,
  frame_ref_id,
  frame_url,
  prompt_score,
  operator_priority_score,
  operator_action,
  reason,
  status,
  operator_note,
  created_at,
  updated_at
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_operator_queue_item_from_second_pass_result(self, *, id: Optional[Any], status: str, second_pass_result_id: str) -> Optional[models.OperatorQueueItem]:
        row = self._conn.execute(sqlalchemy.text(CREATE_OPERATOR_QUEUE_ITEM_FROM_SECOND_PASS_RESULT), {"p1": id, "p2": status, "p3": second_pass_result_id}).first()
        if row is None:
            return None
        return models.OperatorQueueItem(
            id=row[0],
            second_pass_result_id=row[1],
            operation_id=row[2],
            camera_id=row[3],
            camera_group_id=row[4],
            prompt_id=row[5],
            frame_ref_id=row[6],
            frame_url=row[7],
            prompt_score=row[8],
            operator_priority_score=row[9],
            operator_action=row[10],
            reason=row[11],
            status=row[12],
            operator_note=row[13],
            created_at=row[14],
            updated_at=row[15],
        )

    def list_operator_queue_items(self, *, filter_status: Optional[str], offset_count: int, limit_count: int) -> Iterator[models.OperatorQueueItem]:
        result = self._conn.execute(sqlalchemy.text(LIST_OPERATOR_QUEUE_ITEMS), {"p1": filter_status, "p2": offset_count, "p3": limit_count})
        for row in result:
            yield models.OperatorQueueItem(
                id=row[0],
                second_pass_result_id=row[1],
                operation_id=row[2],
                camera_id=row[3],
                camera_group_id=row[4],
                prompt_id=row[5],
                frame_ref_id=row[6],
                frame_url=row[7],
                prompt_score=row[8],
                operator_priority_score=row[9],
                operator_action=row[10],
                reason=row[11],
                status=row[12],
                operator_note=row[13],
                created_at=row[14],
                updated_at=row[15],
            )

    def update_operator_queue_item_status(self, *, status: str, operator_note: Optional[str], id: str) -> Optional[models.OperatorQueueItem]:
        row = self._conn.execute(sqlalchemy.text(UPDATE_OPERATOR_QUEUE_ITEM_STATUS), {"p1": status, "p2": operator_note, "p3": id}).first()
        if row is None:
            return None
        return models.OperatorQueueItem(
            id=row[0],
            second_pass_result_id=row[1],
            operation_id=row[2],
            camera_id=row[3],
            camera_group_id=row[4],
            prompt_id=row[5],
            frame_ref_id=row[6],
            frame_url=row[7],
            prompt_score=row[8],
            operator_priority_score=row[9],
            operator_action=row[10],
            reason=row[11],
            status=row[12],
            operator_note=row[13],
            created_at=row[14],
            updated_at=row[15],
        )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_operator_queue_item_from_second_pass_result(self, *, id: Optional[Any], status: str, second_pass_result_id: str) -> Optional[models.OperatorQueueItem]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_OPERATOR_QUEUE_ITEM_FROM_SECOND_PASS_RESULT), {"p1": id, "p2": status, "p3": second_pass_result_id})).first()
        if row is None:
            return None
        return models.OperatorQueueItem(
            id=row[0],
            second_pass_result_id=row[1],
            operation_id=row[2],
            camera_id=row[3],
            camera_group_id=row[4],
            prompt_id=row[5],
            frame_ref_id=row[6],
            frame_url=row[7],
            prompt_score=row[8],
            operator_priority_score=row[9],
            operator_action=row[10],
            reason=row[11],
            status=row[12],
            operator_note=row[13],
            created_at=row[14],
            updated_at=row[15],
        )

    async def list_operator_queue_items(self, *, filter_status: Optional[str], offset_count: int, limit_count: int) -> AsyncIterator[models.OperatorQueueItem]:
        result = await self._conn.stream(sqlalchemy.text(LIST_OPERATOR_QUEUE_ITEMS), {"p1": filter_status, "p2": offset_count, "p3": limit_count})
        async for row in result:
            yield models.OperatorQueueItem(
                id=row[0],
                second_pass_result_id=row[1],
                operation_id=row[2],
                camera_id=row[3],
                camera_group_id=row[4],
                prompt_id=row[5],
                frame_ref_id=row[6],
                frame_url=row[7],
                prompt_score=row[8],
                operator_priority_score=row[9],
                operator_action=row[10],
                reason=row[11],
                status=row[12],
                operator_note=row[13],
                created_at=row[14],
                updated_at=row[15],
            )

    async def update_operator_queue_item_status(self, *, status: str, operator_note: Optional[str], id: str) -> Optional[models.OperatorQueueItem]:
        row = (await self._conn.execute(sqlalchemy.text(UPDATE_OPERATOR_QUEUE_ITEM_STATUS), {"p1": status, "p2": operator_note, "p3": id})).first()
        if row is None:
            return None
        return models.OperatorQueueItem(
            id=row[0],
            second_pass_result_id=row[1],
            operation_id=row[2],
            camera_id=row[3],
            camera_group_id=row[4],
            prompt_id=row[5],
            frame_ref_id=row[6],
            frame_url=row[7],
            prompt_score=row[8],
            operator_priority_score=row[9],
            operator_action=row[10],
            reason=row[11],
            status=row[12],
            operator_note=row[13],
            created_at=row[14],
            updated_at=row[15],
        )
