name: Deploy CamBot Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-core.yml
    with:
      environment: dev
      branch_environment: dev
    secrets: inherit
