/**
 * Camera System Integrator API
 * Contract implemented by camera system adapters. The Camera System Mocker implements this API for demo/testing.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetCameraStream200Response from '../model/GetCameraStream200Response';
import InlineObject from '../model/InlineObject';

/**
* Streams service.
* @module api/StreamsApi
* @version 0.1.0
*/
export default class StreamsApi {

    /**
    * Constructs a new StreamsApi. 
    * @alias module:api/StreamsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get camera stream descriptor
     * @param {String} cameraId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetCameraStream200Response} and HTTP response
     */
    getCameraStreamWithHttpInfo(cameraId) {
      let postBody = null;
      // verify the required parameter 'cameraId' is set
      if (cameraId === undefined || cameraId === null) {
        throw new Error("Missing the required parameter 'cameraId' when calling getCameraStream");
      }

      let pathParams = {
        'cameraId': cameraId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetCameraStream200Response;
      return this.apiClient.callApi(
        '/cameras/{cameraId}/stream', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get camera stream descriptor
     * @param {String} cameraId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetCameraStream200Response}
     */
    getCameraStream(cameraId) {
      return this.getCameraStreamWithHttpInfo(cameraId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
